import json

filepath = '/media/amit/Other1/webdevelopment/github/mahavyomastudio-apps/app_04_bihar_explorer/src/data/bihar-knowledge/02-history/ancient.json'
with open(filepath, 'r', encoding='utf-8') as f:
    data = json.load(f)

updates = {
    "mahajanapadas-of-bihar": {
        "en": "### The Dawn of Empires\nOut of the sixteen great kingdoms (**Mahajanapadas**) mentioned in early texts such as the Buddhist *Anguttara Nikaya* and the Jain *Bhagavati Sutra*, three primary kingdoms flourished on the sacred land of Bihar. \n\n* **Magadha**: Situated in south-central Bihar, it became the crucible of India's earliest empires.\n* **Anga**: Located in eastern Bihar (modern Bhagalpur and Munger), it was renowned for its wealth and trade.\n* **Vajji**: A powerful confederacy in northern Bihar, known for its republican values.\n\n### Historical Significance\nThese three states were not just political entities; they were centers of profound economic and social transformation. They pioneered:\n* Systematic political consolidation\n* The introduction of coinage\n* The dawn of the second urbanization in ancient India",
        "hi": "### साम्राज्यों का उदय\nप्रारंभिक बौद्ध ग्रंथ *'अंगुत्तर निकाय'* और जैन ग्रंथ *'भगवती सूत्र'* में वर्णित सोलह महान राज्यों (**महाजनपदों**) में से तीन प्रमुख महाजनपद बिहार की पावन भूमि पर फले-फूले।\n\n* **मगध**: दक्षिण-मध्य बिहार में स्थित, यह भारत के सबसे शक्तिशाली साम्राज्यों का केंद्र बना।\n* **अंग**: पूर्वी बिहार (वर्तमान भागलपुर और मुंगेर) में स्थित, यह अपनी अपार संपदा और वाणिज्य के लिए प्रसिद्ध था।\n* **वज्जि**: उत्तरी बिहार का एक शक्तिशाली संघ, जो अपने गणतांत्रिक मूल्यों के लिए जाना जाता था।\n\n### ऐतिहासिक महत्व\nये तीनों राज्य केवल राजनीतिक सत्ता नहीं थे, बल्कि वे गहरे आर्थिक और सामाजिक परिवर्तन के केंद्र भी थे। इन्होंने निम्नलिखित की नींव रखी:\n* सुव्यवस्थित राजनीतिक एकीकरण\n* मौद्रिक प्रणाली की शुरुआत\n* प्राचीन भारत में द्वितीय नगरीकरण का उदय"
    },
    "vajji-licchavi-republic": {
        "en": "### The World's First Republic\nThe **Vajji confederacy**, led by the illustrious Licchavis with its capital at Vaishali, is celebrated globally as the earliest known democratic republic in human history. \n\n### Governance and Administration\nUnlike monarchies where power was concentrated in a single king, the Licchavi republic operated on participatory democracy:\n* Decisions were deliberated transparently in the general assembly known as the **Santhagara**.\n* It featured an elected leadership and a complex judicial system.\n* The society was highly progressive, honoring intellectuals and spiritual leaders alike.\n\n### Enduring Legacy\nThis ancient democratic model deeply inspired **Lord Buddha**, who adapted its governance principles to structure the *Buddhist Sangha* (monastic order), leaving a profound legacy of rule-of-law and collective decision-making.",
        "hi": "### विश्व का प्रथम गणतंत्र\nवैशाली की राजधानी वाला लिच्छवियों का **वज्जि संघ** विश्व इतिहास में प्रथम ज्ञात लोकतांत्रिक गणराज्य के रूप में विख्यात है।\n\n### शासन एवं प्रशासन\nराजतंत्र के विपरीत, जहां सत्ता एक ही राजा में केंद्रित होती थी, लिच्छवि गणराज्य सहभागी लोकतंत्र पर आधारित था:\n* निर्णय राजा के व्यक्तिगत आदेश से नहीं, बल्कि **'संथागार'** नामक जनप्रतिनिधि सभा में मतदान व विचार-विमर्श से लिए जाते थे।\n* इसमें निर्वाचित नेतृत्व और एक जटिल न्याय प्रणाली की व्यवस्था थी।\n* यह समाज अत्यंत प्रगतिशील था, जहां बुद्धिजीवियों और आध्यात्मिक गुरुओं का समान रूप से सम्मान किया जाता था।\n\n### अमिट विरासत\nइस प्राचीन लोकतांत्रिक प्रतिरूप ने **भगवान बुद्ध** को गहराई से प्रेरित किया। उन्होंने बौद्ध संघ के नियमों को गढ़ने के लिए इसी शासन प्रणाली के सिद्धांतों को अपनाया, जिसने विधि के शासन और सामूहिक निर्णय लेने की एक महान विरासत छोड़ी।"
    },
    "haryanka-dynasty": {
        "en": "### The Rise of Magadhan Imperialism\nUnder the reign of **King Bimbisara** and his ambitious son **Ajatashatru**, the Haryanka dynasty transformed Magadha into the supreme imperial power of the Indian subcontinent. \n\n### Key Developments\n* **Strategic Fortifications**: Ajatashatru constructed a formidable defensive fort at *Pataligrama*—at the strategic confluence of the Ganga and Son rivers—to effectively check the power of the Vajji confederacy.\n* **The Capital Shift**: Recognizing its unparalleled geographic advantage, Ajatashatru's son, **Udayin**, subsequently moved the imperial capital from the hilly terrain of Rajgriha to the riverine stronghold of **Pataliputra**.\n\n### Cultural and Spiritual Impact\nThe Haryanka period was immensely significant for spiritual history. Immediately following Lord Buddha's Mahaparinirvana in 483 BCE, Ajatashatru famously patronized the **First Buddhist Council** at the Sattapanni Cave in Rajgir, preserving the Buddha's teachings for posterity.",
        "hi": "### मगध के साम्राज्यवाद का उदय\n**महाराज बिम्बिसार** और उनके महत्त्वाकांक्षी पुत्र **अजातशत्रु** के शासनकाल में, हर्यक वंश ने मगध को भारतीय उपमहाद्वीप की सर्वोच्च साम्राज्यवादी शक्ति के रूप में स्थापित किया।\n\n### प्रमुख विकास\n* **सामरिक किलेबंदी**: अजातशत्रु ने वज्जि संघ की शक्ति को नियंत्रित करने के लिए गंगा और सोन नदियों के सामरिक संगम पर *पाटलिग्राम* में एक अभेद्य सैन्य दुर्ग का निर्माण करवाया।\n* **राजधानी का स्थानांतरण**: इसके अद्वितीय भौगोलिक लाभ को पहचानते हुए, अजातशत्रु के पुत्र **उदयिन** ने साम्राज्य की राजधानी को राजगृह की पहाड़ियों से हटाकर नदी तटीय नगर **पाटलिपुत्र** में स्थानांतरित कर दिया।\n\n### सांस्कृतिक एवं आध्यात्मिक प्रभाव\nहर्यक काल आध्यात्मिक इतिहास के लिए अत्यंत महत्त्वपूर्ण था। 483 ईसा पूर्व में भगवान बुद्ध के महापरिनिर्वाण के तुरंत पश्चात, अजातशत्रु ने राजगीर की सप्तपर्णी गुफा में **प्रथम बौद्ध संगीति** को अपना संरक्षण प्रदान किया, जिससे बुद्ध की शिक्षाएं युगों-युगों के लिए संरक्षित हो गईं।"
    },
    "shishunaga-and-nanda-dynasties": {
        "en": "### The Shishunaga Ascendancy\nThe ascent of **Shishunaga** marked the definitive end of Magadha's long-standing rivalry with the kingdom of Avanti, paving the way for unchallenged Magadhan supremacy. During this era, his successor Kalashoka organized the pivotal **Second Buddhist Council** at Vaishali in 383 BCE.\n\n### The Mighty Nanda Empire\nFollowing the Shishunagas, the formidable **Mahapadma Nanda** established the mighty Nanda Empire. \n\n* **India's First Empire-Builder**: Mahapadma Nanda is historically celebrated as India's first true empire-builder (*Ekarat*).\n* **Formidable Military**: The Nandas maintained an incredibly vast and powerful army. It was the terrifying reputation of this very army that deterred **Alexander the Great's** troops from crossing the Beas river and advancing further into India.\n* **Administrative Centralization**: The Nandas unified northern India under a highly centralized fiscal administration, amassing immense wealth and setting the foundational stage for the subsequent Mauryan Empire.",
        "hi": "### शिशुनाग वंश का उत्कर्ष\n**शिशुनाग** के सत्ता में आने से मगध और अवंती राज्य के बीच सदियों पुरानी प्रतिद्वंद्विता का अंत हुआ, जिसने मगध के निर्विवाद वर्चस्व का मार्ग प्रशस्त किया। इसी काल में, उनके उत्तराधिकारी कालाशोक ने 383 ईसा पूर्व में वैशाली में ऐतिहासिक **द्वितीय बौद्ध संगीति** का आयोजन किया।\n\n### विशाल नंद साम्राज्य\nशिशुनागों के पश्चात, पराक्रमी **महापद्मनंद** ने शक्तिशाली नंद साम्राज्य की स्थापना की।\n\n* **भारत के प्रथम साम्राज्य-निर्माता**: महापद्मनंद को ऐतिहासिक रूप से भारत का प्रथम वास्तविक साम्राज्य-निर्माता (*एकराट*) माना जाता है।\n* **अजेय सेना**: नंदों के पास एक अत्यंत विशाल और शक्तिशाली सेना थी। इसी चतुरंगिणी सेना के खौफ से **सिकंदर महान** की सेना ने ब्यास नदी पार करने और भारत में आगे बढ़ने से इनकार कर दिया था।\n* **प्रशासनिक केंद्रीकरण**: नंदों ने एक अत्यधिक केंद्रीकृत कर-प्रणाली के तहत उत्तरी भारत को एकीकृत किया, अपार संपदा एकत्रित की और आगामी मौर्य साम्राज्य के लिए एक सुदृढ़ आधारशिला तैयार की।"
    },
    "gautama-buddha-enlightenment": {
        "en": "### The Quest for Ultimate Truth\nAfter renouncing royal luxuries, Prince Siddhartha embarked on an arduous spiritual journey. His quest culminated in Bodh Gaya, where he engaged in deep, unwavering meditation under the sacred **Peepal (Bodhi) tree** on the serene banks of the Falgu (Niranjana) River.\n\n### The Dawn of Supreme Enlightenment\nIt was here that he conquered worldly illusions and attained **Supreme Enlightenment (Bodhi)**, transforming from Siddhartha into the *Buddha* (The Awakened One). \n\n* **Birth of Buddhism**: This profound event marked the genesis of Buddhism as a world religion.\n* **Global Spiritual Epicenter**: The site is now immortalized by the magnificent Mahabodhi Temple Complex, recognized universally as a **UNESCO World Heritage Site**.\n* **Message of Peace**: From the soil of Bihar, the Buddha's eternal message of *Karuna* (compassion), *Ahimsa* (non-violence), and the *Middle Path* radiated outwards, profoundly shaping the cultural and spiritual landscape of all of Asia.",
        "hi": "### परम सत्य की खोज\nराजसी सुख-सुविधाओं का त्याग करने के पश्चात्, राजकुमार सिद्धार्थ ने एक कठिन आध्यात्मिक यात्रा आरंभ की। उनकी यह खोज बोधगया में फलीभूत हुई, जहाँ उन्होंने फल्गु (निरंजना) नदी के शांत तट पर पवित्र **पीपल (बोधि) वृक्ष** के नीचे गहन और अटूट ध्यान साधना की।\n\n### संबोधि (ज्ञान) का उदय\nयहीं पर उन्होंने सांसारिक मोह-माया पर विजय प्राप्त की और **परम ज्ञान (संबोधि)** प्राप्त किया, जिससे वे सिद्धार्थ से *'बुद्ध'* (जागृत पुरुष) बन गए।\n\n* **बौद्ध धर्म का जन्म**: यह महान घटना विश्व धर्म के रूप में बौद्ध धर्म की उत्पत्ति का प्रतीक है।\n* **वैश्विक आध्यात्मिक केंद्र**: यह पावन स्थल आज भव्य महाबोधि मंदिर परिसर द्वारा सुशोभित है, जिसे **यूनेस्को की विश्व धरोहर स्थल** के रूप में वैश्विक मान्यता प्राप्त है।\n* **शांति का संदेश**: बिहार की इसी पावन मिट्टी से बुद्ध का *करुणा*, *अहिंसा* और *मध्यम मार्ग* का शाश्वत संदेश पूरे एशिया के सांस्कृतिक और आध्यात्मिक परिदृश्य को आकार देते हुए दुनिया भर में फैल गया।"
    },
    "jain-tirthankaras-in-bihar": {
        "en": "### The Birth of Lord Mahavira\nThe 24th and final Tirthankara of Jainism, **Bhagwan Mahavira**, was born in the sacred environs of Kundalgram near Vaishali. His teachings became the bedrock of modern Jain philosophy.\n\n### The Core Philosophy\nLord Mahavira deeply revitalized the spiritual landscape by emphasizing the five great vows (**Mahavratas**):\n* **Ahimsa** (Non-violence)\n* **Satya** (Truth)\n* **Asteya** (Non-stealing)\n* **Brahmacharya** (Chastity)\n* **Aparigraha** (Non-attachment)\n\n### The Ultimate Liberation (Nirvana)\nIn 527 BCE, Lord Mahavira attained ultimate liberation (*Nirvana*) at **Pavapuri** in the present-day Nalanda district. Today, the breathtaking lotus pond and its central **Jal Mandir** commemorate this divine event. Remarkably, Bihar served as the ascetic proving ground and the land of salvation for 20 out of the 24 Jain Tirthankaras, cementing its status as the holiest realm in Jainism.",
        "hi": "### भगवान महावीर का जन्म\nजैन धर्म के 24वें और अंतिम तीर्थंकर, **भगवान महावीर** का जन्म वैशाली के निकट कुंडलपुर (कुंडलग्राम) के पवित्र वातावरण में हुआ था। उनकी शिक्षाएँ आधुनिक जैन दर्शन का मूल आधार बनीं।\n\n### मूल दर्शन\nभगवान महावीर ने पांच महाव्रतों (**पंच महाव्रत**) पर बल देकर आध्यात्मिक परिदृश्य को गहराई से पुनर्जीवित किया:\n* **अहिंसा**\n* **सत्य**\n* **अस्तेय** (चोरी न करना)\n* **ब्रह्मचर्य**\n* **अपरिग्रह** (संपत्ति का संचय न करना)\n\n### परम मोक्ष (निर्वाण)\n527 ईसा पूर्व में, भगवान महावीर ने वर्तमान नालंदा जिले के **पावापुरी** में परम मोक्ष (*निर्वाण*) प्राप्त किया। आज, वहां का अद्भुत कमल-सरोवर और उसके मध्य स्थित **जल मंदिर** इस दिव्य घटना की स्मृति संजोए हुए है। उल्लेखनीय है कि 24 में से 20 जैन तीर्थंकरों की तपोभूमि और निर्वाणभूमि बिहार ही रही है, जो इसे जैन धर्म का सबसे पवित्र तीर्थस्थल सिद्ध करता है।"
    },
    "maurya-empire": {
        "en": "### The First Pan-Indian Empire\nFounded by the visionary **Chandragupta Maurya** under the astute political guidance of **Acharya Chanakya**, the Mauryan Empire emerged as the first pan-Indian empire. Governed from the magnificent capital of Pataliputra, it unified a fragmented subcontinent into a singular, formidable power.\n\n### The Transformation of Emperor Ashoka\nThe empire reached its zenith under **Emperor Ashoka**. The devastating Kalinga War (c. 261 BCE) triggered a profound spiritual transformation in him. \n\n* **Path of Dhamma**: Ashoka abandoned military conquest in favor of *Dhamma-vijaya* (victory through righteousness and compassion).\n* **Global Peace Missions**: He dispatched peace emissaries and Buddhist monks across Asia, transforming Buddhism into a world religion.\n* **Third Buddhist Council**: Under his royal patronage, the monumental Third Buddhist Council was convened at Pataliputra.\n\n### Enduring Symbols\nThe administrative genius and the ethical edicts of the Mauryas left an immortal legacy. Today, the Republic of India's National Emblem (the **Lion Capital of Ashoka**) and the **Ashoka Chakra** on the National Flag are direct cultural inheritances from Mauryan Bihar.",
        "hi": "### प्रथम अखिल भारतीय साम्राज्य\n**आचार्य चाणक्य** के कुशल राजनीतिक मार्गदर्शन में दूरदर्शी **चंद्रगुप्त मौर्य** द्वारा स्थापित मौर्य साम्राज्य, भारत के प्रथम अखिल भारतीय साम्राज्य के रूप में उभरा। भव्य राजधानी पाटलिपुत्र से संचालित, इसने एक खंडित उपमहाद्वीप को एक एकल, शक्तिशाली साम्राज्य में एकीकृत किया।\n\n### सम्राट अशोक का हृदय परिवर्तन\n**सम्राट अशोक** के शासनकाल में यह साम्राज्य अपने चरमोत्कर्ष पर पहुंचा। विनाशकारी कलिंग युद्ध (लगभग 261 ईसा पूर्व) ने उनके भीतर एक गहरा आध्यात्मिक परिवर्तन ला दिया।\n\n* **धम्म का मार्ग**: अशोक ने सैन्य विजय का त्याग कर *धम्म-विजय* (धर्म और करुणा के माध्यम से विजय) का मार्ग अपनाया।\n* **वैश्विक शांति मिशन**: उन्होंने पूरे एशिया में शांति दूत और बौद्ध भिक्षु भेजे, जिससे बौद्ध धर्म एक वैश्विक धर्म बन गया।\n* **तृतीय बौद्ध संगीति**: उनके शाही संरक्षण में, पाटलिपुत्र में ऐतिहासिक तृतीय बौद्ध संगीति का आयोजन किया गया।\n\n### अमिट प्रतीक\nमौर्यों की प्रशासनिक प्रतिभा और नैतिक शिलालेखों ने एक अमर विरासत छोड़ी है। आज, भारत गणराज्य का राष्ट्रीय प्रतीक (**अशोक का सिंह शीर्ष**) और राष्ट्रीय ध्वज पर अंकित **अशोक चक्र** मौर्यकालीन बिहार की ही प्रत्यक्ष सांस्कृतिक धरोहर हैं।"
    },
    "shunga-kanva-dynasty": {
        "en": "### The Shunga Revolution\nFollowing the decline of the Mauryas, commander-in-chief **Pushyamitra Shunga** overthrew the last Mauryan ruler, Brihadratha, and established the Shunga dynasty at Pataliputra. This transition marked a significant socio-cultural shift in ancient India.\n\n### Vedic Revival and Classical Arts\nThe Shunga period is prominently recognized for a vigorous revival of ancient traditions:\n* **Vedic Rituals**: The royal court reinstated grand Vedic ceremonies, most notably conducting two majestic *Ashvamedha Yagnas* (horse sacrifices).\n* **Literary Excellence**: This era witnessed immense scholarly output, including the monumental grammatical treatise *Mahabhasya* authored by the revered sage **Patanjali**.\n* **Architectural Flourish**: Despite the Vedic resurgence, Buddhist art also thrived magnificently. The period contributed heavily to early classical Indian sculpture, beautifully evidenced by the intricately carved stone railings (*Vedikas*) erected at Bodh Gaya and Bharhut.",
        "hi": "### शुंग क्रांति\nमौर्यों के पतन के पश्चात्, सेनापति **पुष्यमित्र शुंग** ने अंतिम मौर्य शासक बृहद्रथ को अपदस्थ कर पाटलिपुत्र में शुंग वंश की स्थापना की। इस सत्ता परिवर्तन ने प्राचीन भारत में एक महत्वपूर्ण सामाजिक-सांस्कृतिक बदलाव को जन्म दिया।\n\n### वैदिक पुनरुद्धार एवं शास्त्रीय कलाएं\nशुंग काल को मुख्य रूप से प्राचीन परंपराओं के सशक्त पुनरुद्धार के लिए जाना जाता है:\n* **वैदिक अनुष्ठान**: राजदरबार में भव्य वैदिक यज्ञों की पुनः शुरुआत हुई, जिसमें विशेष रूप से दो विशाल *अश्वमेध यज्ञों* का आयोजन किया गया।\n* **साहित्यिक उत्कृष्टता**: इस युग में अपार विद्वतापूर्ण रचनाएं हुईं, जिनमें परम श्रद्धेय महर्षि **पतंजलि** द्वारा रचित महान व्याकरणिक ग्रंथ *महाभाष्य* सर्वप्रमुख है।\n* **वास्तुकला का विकास**: वैदिक पुनरुत्थान के बावजूद, बौद्ध कला का भी शानदार विकास हुआ। इस काल ने प्रारंभिक शास्त्रीय भारतीय मूर्तिकला में भारी योगदान दिया, जिसका उत्कृष्ट प्रमाण बोधगया और भरहुत में निर्मित जटिल नक्काशीदार प्रस्तर वेदिकाओं (रेलिंग) में देखने को मिलता है।"
    },
    "gupta-empire-golden-age": {
        "en": "### The Classical Golden Age\nGoverning from the historic heart of Pataliputra, the **Gupta Empire** ushered India into its most glorious epoch, universally hailed as the classical 'Golden Age'. This era witnessed unprecedented, sublime advancements in art, science, literature, and metallurgy.\n\n### Intellectual and Scientific Pinnacles\nKusumapura (ancient Patna) emerged as a vibrant nucleus of global intellect:\n* **Aryabhata's Genius**: The legendary mathematician and astronomer **Aryabhata** authored the groundbreaking *Aryabhatiya* here.\n* **Mathematical Breakthroughs**: He conceptualized the revolutionary mathematical concept of zero and calculated the near-exact value of pi (π).\n* **Astronomical Discoveries**: Centurys before European astronomers, he accurately theorized the diurnal rotation of the Earth on its axis and the true causes of solar and lunar eclipses.\n\n### Cultural Renaissance\nThe Guptas generously patronized classical Sanskrit literature, magnificent temple architecture, and exquisite stone and bronze sculpture (such as the Sultanganj Buddha), setting a standard of aesthetic beauty that influenced all of Asia.",
        "hi": "### शास्त्रीय स्वर्ण युग\nऐतिहासिक नगर पाटलिपुत्र से शासन करते हुए, **गुप्त साम्राज्य** ने भारत को उसके सबसे गौरवशाली कालखंड में प्रवेश कराया, जिसे सार्वभौमिक रूप से शास्त्रीय 'स्वर्ण युग' कहा जाता है। इस युग ने कला, विज्ञान, साहित्य और धातु विज्ञान में अभूतपूर्व और उत्कृष्ट प्रगति देखी।\n\n### बौद्धिक एवं वैज्ञानिक चरमोत्कर्ष\nकुसुमपुर (प्राचीन पटना) वैश्विक ज्ञान-विज्ञान के एक जीवंत केंद्र के रूप में उभरा:\n* **आर्यभट की प्रतिभा**: महान खगोलशास्त्री और गणितज्ञ **आर्यभट** ने यहीं युगांतकारी ग्रंथ *'आर्यभटीय'* की रचना की।\n* **गणितीय क्रांतियां**: उन्होंने शून्य की क्रांतिकारी गणितीय अवधारणा का प्रतिपादन किया और पाई (π) के लगभग सटीक मान की गणना की।\n* **खगोलीय खोजें**: यूरोपीय खगोलविदों से सदियों पहले, उन्होंने अपनी धुरी पर पृथ्वी के घूर्णन और सूर्य तथा चंद्र ग्रहण के वास्तविक कारणों का सटीक सिद्धांत दिया।\n\n### सांस्कृतिक पुनर्जागरण\nगुप्त सम्राटों ने शास्त्रीय संस्कृत साहित्य, भव्य मंदिर वास्तुकला, और उत्कृष्ट प्रस्तर एवं कांस्य मूर्तिकला (जैसे सुल्तानगंज बुद्ध) को उदारतापूर्वक संरक्षण प्रदान किया, जिसने संपूर्ण एशिया को प्रभावित करने वाले सौंदर्यशास्त्र का एक नया मानक स्थापित किया।"
    },
    "nalanda-mahavihara": {
        "en": "### The Pinnacle of Ancient Learning\nFounded in 427 CE by the Gupta Emperor **Kumaragupta I**, and later lavishly patronized by Emperor Harshavardhana and the Pala kings, **Nalanda Mahavihara** stands as the world's first and most magnificent residential university. \n\n### A Global Academic Hub\nLong before Oxford or Bologna, Nalanda was the undisputed intellectual capital of the Eastern world:\n* **International Student Body**: It hosted over 10,000 scholars and 2,000 venerated teachers drawing brilliant minds from China, Korea, Japan, Tibet, and Central Asia (including famous travelers like *Xuanzang* and *Yijing*).\n* **Diverse Curriculum**: The curriculum went far beyond Buddhist theology, encompassing rigorous studies in logic, epistemology, medicine (*Ayurveda*), mathematics, and advanced metallurgy.\n* **The Great Library**: Its legendary library complex, the **Dharmaganja**, featured three colossal multi-storey towers—*Ratnasagara, Ratnodadhi,* and *Ratnaranjaka*—housing millions of priceless manuscripts.\n\nToday, the excavated ruins of Nalanda are enshrined as a **UNESCO World Heritage Site**, serving as a monumental testament to ancient India's supreme dedication to knowledge.",
        "hi": "### प्राचीन शिक्षा का शिखर\n427 ईस्वी में गुप्त सम्राट **कुमारगुप्त प्रथम** द्वारा स्थापित, और बाद में सम्राट हर्षवर्धन तथा पाल राजाओं द्वारा भव्य रूप से संरक्षित, **नालंदा महाविहार** विश्व के प्रथम और सबसे महान आवासीय विश्वविद्यालय के रूप में प्रतिष्ठित है।\n\n### एक वैश्विक शैक्षणिक केंद्र\nऑक्सफोर्ड या बोलोग्ना से बहुत पहले, नालंदा पूर्वी दुनिया की निर्विवाद बौद्धिक राजधानी थी:\n* **अंतरराष्ट्रीय छात्र समुदाय**: इसमें 10,000 से अधिक विद्वान और 2,000 सम्मानित शिक्षक थे, जो चीन, कोरिया, जापान, तिब्बत और मध्य एशिया (जिसमें *ह्वेनसांग* और *इत्सिंग* जैसे प्रसिद्ध यात्री शामिल हैं) से मेधावी छात्रों को आकर्षित करते थे।\n* **विविध पाठ्यक्रम**: यहां का पाठ्यक्रम केवल बौद्ध धर्मशास्त्र तक सीमित नहीं था, बल्कि इसमें तर्कशास्त्र, ज्ञानमीमांसा, चिकित्सा (*आयुर्वेद*), गणित और उन्नत धातु विज्ञान का गहन अध्ययन शामिल था।\n* **विशाल पुस्तकालय**: इसका ऐतिहासिक पुस्तकालय परिसर, जिसे **धर्मगंज** कहा जाता था, तीन विशाल बहुमंजिला भवनों—*रत्नसागर, रत्नोदधि,* और *रत्नरंजक*—से मिलकर बना था, जिनमें लाखों अमूल्य पांडुलिपियां सुरक्षित थीं।\n\nआज, नालंदा के उत्खनित खंडहरों को **यूनेस्को की विश्व धरोहर स्थल** के रूप में संरक्षित किया गया है, जो ज्ञान के प्रति प्राचीन भारत के सर्वोच्च समर्पण का एक स्मारकीय प्रमाण है।"
    }
}

for item in data['data']:
    if item['id'] in updates:
        item['description'] = updates[item['id']]

with open(filepath, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
    f.write('\n')
