import json

filepath = '/media/amit/Other1/webdevelopment/github/mahavyomastudio-apps/app_04_bihar_explorer/src/data/bihar-knowledge/02-history/medieval.json'
with open(filepath, 'r', encoding='utf-8') as f:
    data = json.load(f)

updates = {
    "pala-empire": {
        "en": "### The Buddhist Renaissance\nThe grand Pala dynasty, founded by **Gopala** (elected to end the *Matsyanyaya* or period of anarchy), ruled the sprawling regions of Bengal and Bihar for over four centuries. \n\n### Centers of Knowledge\n* **Vikramshila Mahavihara**: Established in Bhagalpur by the great **Dharmapala**, this university became a world-renowned center for Tantric *Vajrayana* Buddhism.\n* **Capital Shift**: King **Devapala** strategically moved the imperial capital to *Mudgagiri* (modern Munger) to command the riverine trade routes.\n\n### Artistic Pinnacle\nUnder their benevolent patronage, the Nalanda and Kurkihar schools of bronze casting flourished. Master sculptors like **Dhiman** and **Vitapala** produced sublime black stone and bronze Buddhist statues, setting unprecedented artistic standards in medieval Asia.",
        "hi": "### बौद्ध धर्म का पुनर्जागरण\nमहान पाल वंश, जिसकी स्थापना **गोपाल** ने की थी (जिन्हें *मात्स्यन्याय* या अराजकता को समाप्त करने के लिए जनता ने चुना था), ने चार शताब्दियों से अधिक समय तक बंगाल और बिहार के विशाल क्षेत्रों पर शासन किया।\n\n### ज्ञान के केंद्र\n* **विक्रमशिला महाविहार**: महान सम्राट **धर्मपाल** द्वारा भागलपुर में स्थापित, यह विश्वविद्यालय तांत्रिक *वज्रयान* बौद्ध धर्म का विश्वविख्यात केंद्र बना।\n* **राजधानी परिवर्तन**: सम्राट **देवपाल** ने नदी व्यापार मार्गों पर नियंत्रण रखने के लिए रणनीतिक रूप से साम्राज्य की राजधानी को *मुद्गगिरि* (वर्तमान मुंगेर) में स्थानांतरित किया।\n\n### कला का चरमोत्कर्ष\nइनके उदार संरक्षण में नालंदा और कुर्किहार (गया) की कांस्य मूर्तिकला फली-फूली। **धीमान** और **वीतपाल** जैसे महान शिल्पियों ने काले पत्थर और कांसे की उत्कृष्ट बौद्ध प्रतिमाओं का निर्माण किया, जिसने मध्यकालीन एशिया में अभूतपूर्व कलात्मक मानक स्थापित किए।"
    },
    "karnat-dynasty-mithila": {
        "en": "### The Dawn of the Karnat Dynasty\nFounded in 1097 CE by **Nanyadeva** with its initial royal seat at Simraongarh (along the present Indo-Nepal border), the Karnat dynasty heralded a glorious cultural and literary renaissance in North Bihar (Mithila).\n\n### Cultural and Social Reforms\n* **Preservation of Traditions**: While external invasions troubled much of India, the Karnats preserved traditional Sanskritic law (*Smriti*), astronomical studies, and classical literature.\n* **Panji Prabandha System**: Under the reign of **King Harisimhadeva**, the profound social reform known as *Panji Prabandha* (an elaborate genealogical record-keeping system) was officially institutionalized in 1326 CE.\n\n### Literary Legacy\nThis golden era fostered the ancestral lineage of the immortal poet **Vidyapati**, profoundly enriching the classical Maithili literary traditions and cementing Mithila's identity as a bastion of scholarship.",
        "hi": "### कर्णाट वंश का उदय\n1097 ईस्वी में **नान्यदेव** द्वारा स्थापित, जिसकी प्रारंभिक राजधानी सिमराौनगढ़ (वर्तमान भारत-नेपाल सीमा पर) थी, कर्णाट वंश ने उत्तर बिहार (मिथिला) में एक शानदार सांस्कृतिक और साहित्यिक पुनर्जागरण की शुरुआत की।\n\n### सांस्कृतिक एवं सामाजिक सुधार\n* **परंपराओं का संरक्षण**: जब बाह्य आक्रमणों से भारत का अधिकांश हिस्सा त्रस्त था, तब कर्णाटों ने पारंपरिक धर्मशास्त्र (*स्मृति*), न्याय दर्शन और शास्त्रीय साहित्य को सुरक्षित रखा।\n* **पंजी प्रबंध व्यवस्था**: **राजा हरिसिंहदेव** के शासनकाल में 1326 ईस्वी में *'पंजी प्रबंध'* (एक विस्तृत वंशावली पंजीकरण व्यवस्था) नामक गहन सामाजिक सुधार को संस्थागत रूप दिया गया।\n\n### साहित्यिक विरासत\nइसी स्वर्ण युग ने अमर महाकवि **विद्यापति** के पूर्वज कुल को पोषित किया, जिसने शास्त्रीय मैथिली साहित्य परंपराओं को अत्यधिक समृद्ध किया और विद्या के गढ़ के रूप में मिथिला की पहचान को सुदृढ़ किया।"
    },
    "bakhtiyar-khilji-invasion": {
        "en": "### The Turkic Incursions\nIn the closing years of the 12th century, the Turkic military general **Ikhtiyaruddin Muhammad Bakhtiyar Khilji** initiated devastating campaigns across eastern India, fundamentally altering the historical trajectory of Bihar.\n\n### The Destruction of Mahaviharas\n* **Fall of Odantapuri**: Khilji swiftly captured the heavily fortified monastery of *Odantapuri* (modern Bihar Sharif).\n* **Loss of Knowledge**: Tragically, he raided the globally venerated **Nalanda** and **Vikramshila** Mahaviharas. Their invaluable multi-storey libraries, containing centuries of philosophical and scientific manuscripts, were burnt to ashes.\n\n### Historical Consequences\nThis catastrophic event marked the definitive decline of institutional monastic Buddhism in northern India. It also signaled the onset of Delhi Sultanate suzerainty, drastically shifting the political and cultural landscape of southern Bihar.",
        "hi": "### तुर्क आक्रमण\n12वीं शताब्दी के अंतिम वर्षों में, तुर्क सेनापति **इख्तियारुद्दीन मुहम्मद बख्तियार खिलजी** ने पूर्वी भारत में विनाशकारी सैन्य अभियानों की शुरुआत की, जिसने बिहार के ऐतिहासिक परिदृश्य को मूल रूप से बदल दिया।\n\n### महाविहारों का विध्वंस\n* **ओदंतपुरी का पतन**: खिलजी ने *ओदंतपुरी* (वर्तमान बिहार शरीफ) के सुरक्षित बौद्ध महाविहार पर तेजी से कब्जा कर लिया।\n* **ज्ञान संपदा का नाश**: अत्यंत दुर्भाग्यपूर्ण रूप से, उसने विश्वविख्यात **नालंदा** और **विक्रमशिला** महाविहारों पर आक्रमण किया। सदियों की दार्शनिक और वैज्ञानिक पांडुलिपियों से भरे उनके बहुमंजिला पुस्तकालयों को जलाकर राख कर दिया गया।\n\n### ऐतिहासिक परिणाम\nइस विनाशकारी घटना ने उत्तरी भारत में संस्थागत बौद्ध धर्म के पतन को सुनिश्चित कर दिया। इसने दिल्ली सल्तनत के आधिपत्य की शुरुआत को भी चिह्नित किया, जिससे दक्षिणी बिहार का राजनीतिक और सांस्कृतिक परिदृश्य पूरी तरह से बदल गया।"
    },
    "sufi-traditions-maner-bihar-sharif": {
        "en": "### The Hub of Sufi Mysticism\nDuring the medieval period, Bihar flourished as a vibrant epicenter of Sufi spiritual thought, profoundly shaped by the *Firdausiya* and *Suhrawardiyya* orders. The twin towns of **Maner Sharif** and **Bihar Sharif** became the sanctuaries of this divine movement.\n\n### Teachings of Hazrat Sharfuddin Yahya Maneri\n* **Spiritual Epistles**: Residing amidst the serene Rajgir hills and Bihar Sharif, **Hazrat Makhdum Sharfuddin Yahya Maneri** penned the *Maktubat-e-Sadi* (The Hundred Letters).\n* **Message of Love**: His writings promoted universal humanism, unconditional love, social harmony, and communal fraternity.\n\n### Architectural and Cultural Legacy\nThe majestic **Chhoti Dargah** at Maner, with its exquisite Mughal architecture, and the **Badi Dargah** at Bihar Sharif continue to foster the syncretic *Ganga-Jamuni tehzeeb*, attracting thousands of Hindu and Muslim devotees alike in shared reverence.",
        "hi": "### सूफी रहस्यवाद का केंद्र\nमध्यकाल में, बिहार सूफी आध्यात्मिक विचारों के एक जीवंत केंद्र के रूप में फला-फूला, जो *फिरदौसिया* और *सुहरावर्दिया* सिलसिले से गहराई से प्रभावित था। **मनेर शरीफ** और **बिहार शरीफ** के जुड़वां शहर इस दिव्य आंदोलन की तपोभूमि बन गए।\n\n### हजरत शरफुद्दीन यहिया मनेरी की शिक्षाएं\n* **आध्यात्मिक पत्र**: शांत राजगीर पहाड़ियों और बिहार शरीफ में साधना करते हुए, **हजरत मखदूम शरफुद्दीन यहिया मनेरी** ने *'मकतूबात-ए-सदी'* (सौ पत्रों का संकलन) की रचना की।\n* **प्रेम का संदेश**: उनके लेखों ने सार्वभौमिक मानवता, निस्वार्थ प्रेम, सामाजिक समरसता और सांप्रदायिक भाईचारे को बढ़ावा दिया।\n\n### स्थापत्य एवं सांस्कृतिक विरासत\nमनेर स्थित भव्य मुगल वास्तुकला वाली **छोटी दरगाह**, और बिहार शरीफ की **बड़ी दरगाह** आज भी समकालिक *'गंगा-जमुनी तहजीब'* को पोषित करती हैं, जहां हिंदू और मुस्लिम दोनों धर्मों के श्रद्धालु समान श्रद्धा के साथ शीश नवाते हैं।"
    },
    "suri-empire-sher-shah": {
        "en": "### The Rise of Farid Khan\nBorn in Sasaram, Farid Khan rose through sheer military brilliance and administrative genius to become **Sher Shah Suri**. He decisively defeated Mughal Emperor Humayun at Chausa (1539) and Kannauj (1540), establishing the formidable Suri Empire.\n\n### Revolutionary Administration\nIn his brief but extraordinarily impactful five-year reign, Sher Shah laid the foundations of modern Indian public administration:\n* **Economic Reforms**: He introduced the standardized silver coin called the **'Rupiya'**, the direct ancestor of the modern Indian Rupee.\n* **Land Revenue**: He revolutionized agrarian administration by introducing the *Patta* (title deed) and *Qabuliyat* (agreement) system.\n* **Infrastructure and Urbanization**: He constructed the legendary *Sadak-e-Azam* (Grand Trunk Road) and famously revived ancient Pataliputra as modern **Patna** in 1541.\n\n### Enduring Monument\nHis magnificent octagonal tomb in **Sasaram**, built in the center of an artificial lake, remains a masterpiece of Indo-Islamic architecture.",
        "hi": "### फरीद खां का उदय\nसासाराम में जन्मे फरीद खां ने अपनी सैन्य प्रतिभा और प्रशासनिक कौशल के बल पर **'शेरशाह सूरी'** की उपाधि अर्जित की। उन्होंने चौसा (1539) और कन्नौज (1540) के युद्ध में मुगल सम्राट हुमायूं को निर्णायक रूप से पराजित कर शक्तिशाली सूर साम्राज्य की स्थापना की।\n\n### क्रांतिकारी प्रशासन\nअपने संक्षिप्त लेकिन असाधारण रूप से प्रभावशाली 5 वर्षों के शासन में, शेरशाह ने आधुनिक भारतीय लोक प्रशासन की नींव रखी:\n* **आर्थिक सुधार**: उन्होंने **'रुपया'** नामक मानक चांदी का सिक्का चलाया, जो आधुनिक भारतीय रुपये का प्रत्यक्ष पूर्वज है।\n* **भू-राजस्व**: उन्होंने *'पट्टा'* और *'कबूलियत'* प्रणाली की शुरुआत कर कृषि प्रशासन में क्रांति ला दी।\n* **बुनियादी ढांचा और शहरीकरण**: उन्होंने ऐतिहासिक *सड़क-ए-आजम* (ग्रैंड ट्रंक रोड) का निर्माण कराया और 1541 में प्राचीन पाटलिपुत्र को आधुनिक **पटना** के रूप में पुनर्जीवित किया।\n\n### अमर स्मारक\n**सासाराम** में एक कृत्रिम झील के बीचों-बीच स्थित उनका भव्य अष्टकोणीय मकबरा, इंडो-इस्लामिक वास्तुकला की एक उत्कृष्ट कृति है।"
    },
    "akbars-annexation-bihar-subah": {
        "en": "### The Mughal Naval Campaign\nIn 1574, sensing the rising Afghan threat, **Mughal Emperor Akbar** personally led a massive military expedition down the river Ganga. Utilizing a formidable riverine flotilla, he successfully captured the strategic forts of Hajipur and Patna from the ambitious Afghan ruler, **Daud Khan Karrani**.\n\n### The Birth of Bihar Subah\nFollowing Daud Khan's decisive defeat at the Battle of Rajmahal in 1576, Akbar structurally reorganized the empire.\n* **Administrative Integration**: Bihar was formally integrated into the Mughal Empire as a distinct, powerful province known as a **Subah**, subdivided into seven *Sarkars* (districts).\n* **Economic Boom**: This integration seamlessly connected Bihar to the imperial trade network linking Delhi, Agra, and the Bay of Bengal.\n* **Commercial Prosperity**: Consequently, Patna witnessed a rapid commercial boom, especially in the lucrative trade of saltpetre, indigenous textiles, and high-quality indigo.",
        "hi": "### मुगल नौसैन्य अभियान\n1574 ईस्वी में, अफगान खतरे को भांपते हुए, **मुगल बादशाह अकबर** ने स्वयं गंगा नदी के रास्ते एक विशाल सैन्य अभियान का नेतृत्व किया। एक दुर्जेय जलसेना का उपयोग करते हुए, उन्होंने महत्वाकांक्षी अफगान शासक **दाऊद खां कर्रानी** से हाजीपुर और पटना के रणनीतिक किलों को सफलतापूर्वक जीत लिया।\n\n### बिहार सूबे का जन्म\n1576 में राजमहल के युद्ध में दाऊद खां की निर्णायक हार के बाद, अकबर ने साम्राज्य का पुनर्गठन किया।\n* **प्रशासनिक एकीकरण**: बिहार को औपचारिक रूप से मुगल साम्राज्य में एक अलग और शक्तिशाली प्रांत (**सूबा**) के रूप में शामिल किया गया, जिसे सात *सरकारों* (जिलों) में विभाजित किया गया था।\n* **आर्थिक उछाल**: इस एकीकरण ने बिहार को दिल्ली, आगरा और बंगाल की खाड़ी को जोड़ने वाले साम्राज्यिक व्यापार नेटवर्क से निर्बाध रूप से जोड़ दिया।\n* **व्यावसायिक समृद्धि**: परिणामस्वरूप, पटना ने विशेष रूप से शोरा (सॉल्टपीटर), स्वदेशी वस्त्र और उच्च गुणवत्ता वाले नील के आकर्षक व्यापार में तेजी से उछाल देखा।"
    },
    "raja-man-singh-governorship": {
        "en": "### The Zenith of Mughal Architecture in Bihar\nWhen Emperor Akbar appointed the illustrious Rajput general **Raja Man Singh** as the Governor (*Subahdar*) of Bihar in 1587, it heralded an era of unprecedented architectural and political stabilization.\n\n### The Rohtasgarh Stronghold\n* **Strategic Capital**: Raja Man Singh astutely chose the lofty, impregnable plateau fortress of **Rohtasgarh** as his administrative capital.\n* **Palace Construction**: Within this ancient fort, he constructed an opulent, multi-storey palace complex (*Mahal-e-Sarai*) that brilliantly fused Rajput courtyards and *jharokhas* with elegant Mughal arches.\n\n### Consolidation and Restoration\nBeyond architecture, Man Singh successfully subjugated recalcitrant local chieftains across Gidhaur, Kharagpur, and Bhojpur, firmly establishing Mughal law and order. A devout Hindu, he also generously financed the restoration of monumental, ancient shrines in **Gaya** and **Baidyanath**, bridging cultural divides through royal patronage.",
        "hi": "### बिहार में मुगल वास्तुकला का चरमोत्कर्ष\nजब सम्राट अकबर ने 1587 में प्रसिद्ध राजपूत सेनापति **राजा मानसिंह** को बिहार का सूबेदार नियुक्त किया, तो इससे अभूतपूर्व स्थापत्य और राजनीतिक स्थिरता के युग की शुरुआत हुई।\n\n### रोहतासगढ़ का दुर्ग\n* **रणनीतिक राजधानी**: राजा मानसिंह ने अपनी प्रशासनिक राजधानी के रूप में **रोहतासगढ़** के ऊंचे, अजेय पठारी किले को चुना।\n* **महल का निर्माण**: इस प्राचीन किले के भीतर, उन्होंने एक भव्य, बहुमंजिला महल परिसर (*महले सराय*) का निर्माण किया, जिसमें राजपूत आंगनों और *झरोखों* को सुरुचिपूर्ण मुगल मेहराबों के साथ बड़ी ही कुशलता से मिलाया गया था।\n\n### सुदृढ़ीकरण और जीर्णोद्धार\nवास्तुकला से परे, मानसिंह ने गिद्धौर, खड़गपुर और भोजपुर के विद्रोही स्थानीय सरदारों को सफलतापूर्वक नियंत्रित किया और मुगल कानून-व्यवस्था को दृढ़ता से स्थापित किया। एक परम हिंदू भक्त होने के नाते, उन्होंने **गया** और **बैद्यनाथ** के ऐतिहासिक मंदिरों के जीर्णोद्धार के लिए उदारतापूर्वक धन भी दिया।"
    },
    "guru-gobind-singh-birth-patna-sahib": {
        "en": "### The Divine Birth in Patna\nOn the auspicious day of December 22, 1666 (*Poh Sudi 7*), the Tenth and final human Guru of the Sikhs, **Guru Gobind Singh Ji** (born Gobind Rai), incarnated in the historic city of Patna. He was the son of the Ninth Guru, **Guru Tegh Bahadur Ji**, and **Mata Gujri Ji**.\n\n### The Sacred Childhood\nBefore eventually moving to Anandpur Sahib, the young Guru spent his early formative years playing along the sacred banks of the River Ganga in Patna. His divine childhood (*Bal Leela*) is warmly documented in Sikh traditions, bringing immense joy to the local *sangat*.\n\n### Takht Sri Patna Sahib\nTo honor his birthplace, the majestic **Takht Sri Harmandir Ji Patna Sahib** was later built by Maharaja Ranjit Singh. Today, it stands as one of the Five holy *Takhts* (seats of temporal authority) of Sikhism. It is globally revered as a supreme pilgrimage site, drawing millions during the grand international **Prakash Parv** celebrations.",
        "hi": "### पटना में दिव्य प्रकाश\n22 दिसंबर 1666 (*पोष सुदी 7*) के शुभ दिन, सिखों के दसवें और अंतिम देहधारी गुरु, **श्री गुरु गोबिंद सिंह जी** (बचपन का नाम गोबिंद राय) का ऐतिहासिक नगर पटना में अवतार हुआ। वे नौवें गुरु, **श्री गुरु तेग बहादुर जी**, और **माता गुजरी जी** के सुपुत्र थे।\n\n### पवित्र बाल्यकाल\nआनंदपुर साहिब जाने से पूर्व, बाल गुरु ने अपने शुरुआती वर्ष पटना में गंगा नदी के पावन तटों पर खेलते हुए व्यतीत किए। उनकी दिव्य बाल लीलाएं सिख परंपराओं में बड़ी ही आत्मीयता से दर्ज हैं, जिसने स्थानीय *संगत* को अपार आनंद प्रदान किया।\n\n### तख्त श्री पटना साहिब\nउनके जन्मस्थान को सम्मानित करने के लिए, बाद में महाराजा रणजीत सिंह द्वारा भव्य **'तख्त श्री हरिमंदिर जी पटना साहिब'** का निर्माण किया गया। आज, यह सिख धर्म के पांच पवित्र *तख्तों* में से एक के रूप में खड़ा है। यह एक सर्वोच्च तीर्थस्थल के रूप में विश्व स्तर पर पूजनीय है, जहां भव्य अंतरराष्ट्रीय **प्रकाश पर्व** समारोह के दौरान लाखों श्रद्धालु दर्शनार्थ आते हैं।"
    },
    "prince-azim-us-shan-azimabad": {
        "en": "### The Royal Transformation of Patna\nIn 1703, the twilight years of Emperor Aurangzeb's reign saw his grandson, **Prince Azim-us-Shan**, appointed as the Subahdar of Bihar. His arrival marked a dramatic renaissance for the city of Patna.\n\n### The Era of Azimabad\n* **A New Metropolis**: Captivated by the city, the Prince officially renamed Patna as **'Azimabad'**.\n* **Imperial Investments**: He spent a staggering royal sum of one crore rupees to redesign and beautify it, intending to elevate Azimabad into a magnificent imperial metropolis that could rival the splendor of Delhi itself.\n* **Royal Ascension**: The city's prestige peaked when Azim-us-Shan's son, **Farrukhsiyar**, was officially crowned Mughal Emperor right here in Patna in 1713.\n\n### Cultural Flourish\nUnder this royal patronage, Azimabad flourished into a renowned center of high culture, particularly famed for Persian and Urdu poetry. It birthed legendary poets like *Bismil Azimabadi* and *Shad Azimabadi*, deeply enriching India's literary heritage.",
        "hi": "### पटना का शाही कायाकल्प\n1703 ईस्वी में, सम्राट औरंगजेब के शासनकाल के अंतिम वर्षों में उनके पौत्र, **शहजादा अजीम-उस-शान** को बिहार का सूबेदार नियुक्त किया गया। उनका आगमन पटना शहर के लिए एक नाटकीय पुनर्जागरण का प्रतीक था।\n\n### अजीमाबाद का स्वर्णकाल\n* **एक नया महानगर**: शहर से मंत्रमुग्ध होकर, शहजादे ने आधिकारिक तौर पर पटना का नाम बदलकर **'अजीमाबाद'** रख दिया।\n* **शाही निवेश**: उन्होंने इसे फिर से डिजाइन करने और संवारने के लिए एक करोड़ रुपये की भारी शाही राशि खर्च की, जिसका उद्देश्य अजीमाबाद को एक ऐसे शानदार महानगर के रूप में विकसित करना था जो स्वयं दिल्ली के वैभव को टक्कर दे सके।\n* **शाही राज्याभिषेक**: शहर की प्रतिष्ठा तब अपने चरम पर पहुंच गई जब अजीम-उस-शान के पुत्र, **फर्रुखसियर** का 1713 में पटना में ही मुगल सम्राट के रूप में राज्याभिषेक हुआ।\n\n### सांस्कृतिक विकास\nइस शाही संरक्षण में, अजीमाबाद उच्च संस्कृति का एक प्रसिद्ध केंद्र बन गया, जो विशेष रूप से फारसी और उर्दू शायरी के लिए विख्यात था। इसने *बिस्मिल अजीमाबादी* और *शाद अजीमाबादी* जैसे महान शायरों को जन्म दिया, जिन्होंने भारत की साहित्यिक विरासत को गहराई से समृद्ध किया।"
    },
    "alivardi-khan-nawabs-of-bengal": {
        "en": "### The Bengal Annexation\nBy 1733, as the Mughal central authority waned, the province of Bihar was merged administratively under the ambit of the Nawab of Bengal. Nawab Shuja-ud-Din decisively appointed the capable military commander **Alivardi Khan** as the *Naib Nazim* (Deputy Governor) of Bihar, seated at Patna.\n\n### The Rise of Alivardi Khan\n* **Suppression of Rebellions**: Operating from Patna, Alivardi Khan effectively streamlined the administration and systematically crushed recalcitrant local chieftains and Afghan uprisings.\n* **Ascension to the Throne**: His spectacular success in Bihar provided him the military and financial leverage to eventually seize the absolute Nawabship of Bengal in 1740.\n\n### The Final Twilight\nFollowing Alivardi Khan's elevation, his nephew and son-in-law, **Haibat Jang**, took over the governorship of Patna until his tragic assassination by Afghan rebels. This period represents the final, dramatic twilight of independent provincial Muslim rule in eastern India, setting the stage for the imminent ascension of the British East India Company.",
        "hi": "### बंगाल का आधिपत्य\n1733 तक, मुगल केंद्रीय सत्ता के कमजोर होने पर, बिहार प्रांत को प्रशासनिक रूप से बंगाल के नवाब के अधीन कर दिया गया। नवाब शुजाउद्दीन ने एक योग्य सैन्य कमांडर **अलीवर्दी खां** को पटना में बिहार का *नायब नाजिम* (उप-सूबेदार) नियुक्त किया।\n\n### अलीवर्दी खां का उदय\n* **विद्रोहों का दमन**: पटना से कार्य करते हुए, अलीवर्दी खां ने प्रशासन को सुव्यवस्थित किया और स्थानीय विद्रोही सरदारों तथा अफगान विद्रोहों को कुचल दिया।\n* **नवाब की गद्दी पर अधिकार**: बिहार में उनकी शानदार सफलता ने उन्हें वह सैन्य और वित्तीय लाभ प्रदान किया जिसके बल पर उन्होंने 1740 में बंगाल की नवाबी पर अधिकार कर लिया।\n\n### अंतिम दौर\nअलीवर्दी खां के नवाब बनने के बाद, उनके भतीजे और दामाद, **हैबत जंग** ने पटना का शासन संभाला, जब तक कि अफगान विद्रोहियों द्वारा उनकी हत्या नहीं कर दी गई। यह अवधि पूर्वी भारत में स्वतंत्र प्रांतीय नवाबों के शासन के अंतिम, नाटकीय दौर को दर्शाती है, जिसने ब्रिटिश ईस्ट इंडिया कंपनी के आसन्न उदय के लिए मंच तैयार किया।"
    }
}

for item in data['data']:
    if item['id'] in updates:
        item['description'] = updates[item['id']]

with open(filepath, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
    f.write('\n')
