import json

filepath = '/media/amit/Other1/webdevelopment/github/mahavyomastudio-apps/app_04_bihar_explorer/src/data/bihar-knowledge/02-history/important-events.json'
with open(filepath, 'r', encoding='utf-8') as f:
    data = json.load(f)

updates = {
    "event-buddha-enlightenment-528-bce": {
        "en": "### The Supreme Awakening\nAfter years of rigorous ascetic wandering and self-mortification, Prince Siddhartha Gautama arrived at the serene banks of the Niranjana (Falgu) river in Bodh Gaya. Seated in deep, unshakeable contemplation on the *Vajrasana* beneath the sacred Bodhi Tree, he engaged in a profound spiritual battle.\n\n### The Birth of the Buddha\nOn the luminous full moon night of Vaishakha, he decisively overcame the psychological temptations of *Mara* (the demon of illusion). \n* **The Noble Truths**: He realized the profound reality of suffering, its cause, and the path to its cessation—the *Four Noble Truths* and the *Noble Eightfold Path*.\n* **A Global Philosophy**: This singular event birthed Buddhism, transforming an ascetic prince into the *Buddha* (The Awakened One). His teachings of *Karuna* (compassion) and *Ahimsa* (non-violence) would eventually sweep across Asia, fundamentally altering global philosophy, ethics, and art.",
        "hi": "### परम जागरण\nवर्षों के कठोर तप और आत्म-पीड़ा के बाद, राजकुमार सिद्धार्थ गौतम बोधगया में निरंजना (फल्गु) नदी के शांत तट पर पहुंचे। पवित्र बोधि वृक्ष के नीचे *वज्रासन* पर गहन, अडिग ध्यान में बैठकर, उन्होंने एक गहरा आध्यात्मिक युद्ध लड़ा।\n\n### बुद्ध का जन्म\nवैशाख पूर्णिमा की उजली रात में, उन्होंने *मार* (भ्रम के राक्षस) के मनोवैज्ञानिक प्रलोभनों पर निर्णायक विजय प्राप्त की।\n* **आर्य सत्य**: उन्होंने दुःख की गहन वास्तविकता, उसके कारण और उसके निवारण के मार्ग—*चार आर्य सत्य* और *अष्टांगिक मार्ग*—का साक्षात्कार किया।\n* **एक वैश्विक दर्शन**: इस अद्वितीय घटना ने बौद्ध धर्म को जन्म दिया, जिसने एक तपस्वी राजकुमार को *'बुद्ध'* (जागृत पुरुष) में बदल दिया। *करुणा* और *अहिंसा* की उनकी शिक्षाएं अंततः पूरे एशिया में फैल गईं, जिसने वैश्विक दर्शन, नैतिकता और कला को मूल रूप से बदल दिया।"
    },
    "event-mahavira-nirvana-527-bce": {
        "en": "### The Final Sermons\nAt the venerable age of 72, the 24th and final Jain Tirthankara, **Bhagwan Mahavira**, arrived at the tranquil town of Pavapuri. Over two consecutive days, he delivered his profound final sermons to his disciples, which are meticulously recorded in the sacred *Uttaradhyayana Sutra*.\n\n### Attainment of Moksha (Nirvana)\nOn the dark, moonless night of *Kartik Amavasya*, Bhagwan Mahavira successfully shed all remaining karmic bonds and attained absolute liberation (*Moksha* or *Nirvana*).\n* **The Festival of Deepawali**: To symbolize the eternal light of his spiritual knowledge against the darkness of ignorance, devoted followers illuminated countless earthen lamps. This momentous act initiated the magnificent festival of Deepawali in the Jain tradition.\n* **The Jal Mandir**: Today, the breathtaking lotus pond and its central *Jal Mandir* mark the exact site of his physical cremation, standing as one of the holiest pilgrimage destinations globally.",
        "hi": "### अंतिम देशना\n72 वर्ष की पूजनीय आयु में, 24वें और अंतिम जैन तीर्थंकर, **भगवान महावीर**, पावापुरी के शांत नगर में पहुंचे। लगातार दो दिनों तक, उन्होंने अपने शिष्यों को अपना गहन अंतिम उपदेश दिया, जो पवित्र *उत्तराध्ययन सूत्र* में सावधानीपूर्वक दर्ज है।\n\n### मोक्ष (निर्वाण) की प्राप्ति\n*कार्तिक अमावस्या* की अंधेरी रात को, भगवान महावीर ने सफलतापूर्वक सभी शेष कर्म बंधनों को तोड़ दिया और पूर्ण मुक्ति (*मोक्ष* या *निर्वाण*) प्राप्त की।\n* **दीपावली का पर्व**: अज्ञानता के अंधकार के खिलाफ उनके आध्यात्मिक ज्ञान के शाश्वत प्रकाश का प्रतीक बनने के लिए, समर्पित अनुयायियों ने अनगिनत मिट्टी के दीपक जलाए। इस महत्वपूर्ण कार्य ने जैन परंपरा में दीपावली के शानदार त्योहार की शुरुआत की।\n* **जल मंदिर**: आज, आश्चर्यजनक कमल-सरोवर और उसका केंद्रीय *जल मंदिर* उनके अंतिम संस्कार के सटीक स्थल को चिह्नित करता है, जो विश्व स्तर पर सबसे पवित्र तीर्थ स्थलों में से एक है।"
    },
    "event-first-buddhist-council-483-bce": {
        "en": "### The Preservation of the Dhamma\nShortly following Lord Buddha's *Mahaparinirvana* in 483 BCE, there was an urgent need to codify and preserve his vast, unwritten teachings. Under the powerful royal patronage of King **Ajatashatru**, the First Buddhist Council was hastily convened in the serene **Sattapanni Cave** at Rajgriha.\n\n### Codifying the Tripitaka\nPresided over by the venerable senior monk **Mahakassapa**, the council brought together 500 enlightened Arahats.\n* **The Discourses**: *Ananda*, the Buddha's closest attendant, recited the *Sutta Pitaka* from his flawless memory, preserving the philosophical discourses.\n* **The Discipline**: *Upali* meticulously recited the *Vinaya Pitaka*, codifying the stringent monastic rules and discipline.\n\nThis monumental council successfully institutionalized the oral traditions, laying the absolute foundational canonical scripture for Buddhism before written records existed.",
        "hi": "### धम्म का संरक्षण\n483 ईसा पूर्व में भगवान बुद्ध के *महापरिनिर्वाण* के कुछ ही समय बाद, उनके विशाल, अलिखित उपदेशों को संकलित करने और संरक्षित करने की तत्काल आवश्यकता महसूस की गई। महाराज **अजातशत्रु** के शक्तिशाली शाही संरक्षण में, राजगृह की शांत **सप्तपर्णी गुफा** में प्रथम बौद्ध संगीति का आयोजन किया गया।\n\n### त्रिपिटक का संकलन\nपूजनीय वरिष्ठ भिक्षु **महाकस्सप** की अध्यक्षता में, इस परिषद ने 500 प्रबुद्ध अरहंतों को एक साथ लाया।\n* **उपदेश**: बुद्ध के सबसे करीबी सेवक *आनंद* ने अपनी दोषरहित स्मृति से *सुत्तपिटक* का पाठ किया, जिससे दार्शनिक उपदेश संरक्षित हुए।\n* **अनुशासन**: *उपाली* ने बड़ी सावधानी से *विनयपिटक* का पाठ किया, जिसने सख्त मठवासी नियमों और अनुशासन को संहिताबद्ध किया।\n\nइस स्मारकीय परिषद ने मौखिक परंपराओं को सफलतापूर्वक संस्थागत रूप दिया, लिखित अभिलेखों के अस्तित्व में आने से पहले ही बौद्ध धर्म के लिए पूर्ण मूलभूत विहित ग्रंथ की नींव रखी।"
    },
    "event-pataliputra-founded-460-bce": {
        "en": "### A Masterstroke of Geopolitics\nRecognizing the unparalleled geopolitical, military, and commercial advantage of the strategic confluence of the Ganga, Son, Gandak, and Punpun rivers, King **Udayin** (son of Ajatashatru) made a historic decision in c. 460 BCE. He founded the grand riverside fortress city of **Pataliputra**.\n\n### The Imperial Capital\nShifting the imperial seat from the hilly, landlocked terrain of Rajgriha, Pataliputra swiftly blossomed into an invincible political nerve center.\n* **A Millennium of Dominance**: It served as the continuous, unbroken imperial capital for the Haryanka, Nanda, Maurya, Shunga, and early Gupta dynasties for nearly a thousand years.\n* **A Global Metropolis**: Described with sheer awe by Greek diplomat *Megasthenes* as a city with majestic wooden palisades, 64 gates, and 570 watchtowers, Pataliputra emerged as one of the largest, wealthiest, and most cosmopolitan metropolises of the ancient world.",
        "hi": "### भू-राजनीति का मास्टरस्ट्रोक\nगंगा, सोन, गंडक और पुनपुन नदियों के रणनीतिक संगम के अद्वितीय भू-राजनीतिक, सैन्य और वाणिज्यिक लाभ को पहचानते हुए, राजा **उदयिन** (अजातशत्रु के पुत्र) ने 460 ईसा पूर्व में एक ऐतिहासिक निर्णय लिया। उन्होंने नदी किनारे के भव्य किलेबंद शहर **पाटलिपुत्र** की स्थापना की।\n\n### साम्राज्य की राजधानी\nराजगृह के पहाड़ी, भूमि से घिरे इलाके से साम्राज्य की गद्दी को स्थानांतरित करते हुए, पाटलिपुत्र तेजी से एक अजेय राजनीतिक केंद्र के रूप में विकसित हुआ।\n* **वर्चस्व की एक सहस्राब्दी**: इसने लगभग एक हजार वर्षों तक हर्यक, नंद, मौर्य, शुंग और प्रारंभिक गुप्त राजवंशों के लिए निरंतर, अटूट साम्राज्यिक राजधानी के रूप में कार्य किया।\n* **एक वैश्विक महानगर**: यूनानी राजनयिक *मेगस्थनीज* द्वारा भव्य लकड़ी की प्राचीर, 64 द्वारों और 570 प्रहरी दुर्गों वाले शहर के रूप में विस्मय के साथ वर्णित, पाटलिपुत्र प्राचीन विश्व के सबसे बड़े, सबसे धनी और महानगरीय शहरों में से एक के रूप में उभरा।"
    },
    "event-ashoka-kalinga-and-dhamma-261-bce": {
        "en": "### The Agony of Kalinga\nIn c. 261 BCE, **Emperor Ashoka** unleashed a devastating military campaign against the independent state of Kalinga. While the Mauryans emerged victorious, the horrific slaughter of over 100,000 people and the massive displacement plunged Ashoka into profound psychological remorse and existential despair.\n\n### The Path of Dhamma (Righteousness)\nRepenting the bloodshed, Ashoka dramatically renounced war (*Bherighosha*) and wholeheartedly embraced Buddhism. \n* **Moral Conquest**: He promulgated his revolutionary policy of *Dhamma-vijaya* (conquest through righteousness, religious tolerance, and non-violence), heavily inscribing these edicts on pillars and rocks across the subcontinent.\n* **Global Missions**: Around 250 BCE, he convened the **Third Buddhist Council** at Pataliputra. Subsequently, he dispatched international peace and Buddhist missions to Sri Lanka, Greece, Syria, and Southeast Asia.\n\nThis stunning transformation turned a regional sect into a major world religion and established the first known welfare state based entirely on moral conscience.",
        "hi": "### कलिंग की पीड़ा\n261 ईसा पूर्व में, **सम्राट अशोक** ने कलिंग के स्वतंत्र राज्य के खिलाफ एक विनाशकारी सैन्य अभियान चलाया। यद्यपि मौर्य विजयी हुए, 1,00,000 से अधिक लोगों के भयानक नरसंहार और बड़े पैमाने पर विस्थापन ने अशोक को गहरे मनोवैज्ञानिक पश्चाताप और अस्तित्व के संकट में डाल दिया।\n\n### धम्म (धर्म) का मार्ग\nरक्तपात पर पश्चाताप करते हुए, अशोक ने नाटकीय रूप से युद्ध (*भेरीघोष*) का त्याग कर दिया और पूरे मन से बौद्ध धर्म अपना लिया।\n* **नैतिक विजय**: उन्होंने *धम्म-विजय* (धर्म, धार्मिक सहिष्णुता और अहिंसा के माध्यम से विजय) की अपनी क्रांतिकारी नीति को प्रख्यापित किया, इन शिलालेखों को पूरे उपमहाद्वीप में स्तंभों और चट्टानों पर भारी मात्रा में उत्कीर्ण कराया।\n* **वैश्विक मिशन**: लगभग 250 ईसा पूर्व में, उन्होंने पाटलिपुत्र में **तृतीय बौद्ध संगीति** बुलाई। तत्पश्चात, उन्होंने श्रीलंका, यूनान, सीरिया और दक्षिण पूर्व एशिया में अंतरराष्ट्रीय शांति और बौद्ध मिशन भेजे।\n\nइस आश्चर्यजनक परिवर्तन ने एक क्षेत्रीय संप्रदाय को एक प्रमुख विश्व धर्म में बदल दिया और पूरी तरह से नैतिक विवेक पर आधारित पहला ज्ञात कल्याणकारी राज्य स्थापित किया।"
    },
    "event-nalanda-founded-427-ce": {
        "en": "### The Temple of Learning\nIn the year 427 CE, the visionary Gupta Emperor **Kumaragupta I** (Shakraditya) laid the foundation of the monastic university of **Nalanda Mahavihara**. This act birthed what would become the pinnacle of classical Asian intellect and the world's first true residential university.\n\n### A Thriving Global Campus\nOver seven glorious centuries, Nalanda expanded exponentially into a sprawling, meticulously planned campus.\n* **Unmatched Infrastructure**: It featured 11 massive monasteries, 6 towering temples, serene meditation parks, and serene lakes.\n* **International Acclaim**: Over 10,000 brilliant scholars and 2,000 savants from China, Japan, Korea, Tibet, and Central Asia congregated here to study logic, philosophy, astronomy, and advanced medicine.\n* **Dharmaganja**: Its legendary multi-storey library complex securely housed hundreds of thousands of rare handwritten palm-leaf and birch-bark manuscripts.\n\nNalanda stands as humanity's most majestic ancient tribute to the fearless pursuit of universal knowledge.",
        "hi": "### ज्ञान का मंदिर\nवर्ष 427 ईस्वी में, दूरदर्शी गुप्त सम्राट **कुमारगुप्त प्रथम** (शक्रादित्य) ने **नालंदा महाविहार** नामक विश्वविद्यालय की नींव रखी। इस कार्य ने उस संस्था को जन्म दिया जो शास्त्रीय एशियाई बुद्धि का शिखर और विश्व का पहला सच्चा आवासीय विश्वविद्यालय बन गया।\n\n### एक जीवंत वैश्विक परिसर\nसात गौरवशाली शताब्दियों के दौरान, नालंदा का एक विशाल, सावधानीपूर्वक नियोजित परिसर में तेजी से विस्तार हुआ।\n* **अद्वितीय बुनियादी ढांचा**: इसमें 11 विशाल विहार, 6 ऊंचे मंदिर, शांत ध्यान पार्क और निर्मल झीलें थीं।\n* **अंतरराष्ट्रीय ख्याति**: चीन, जापान, कोरिया, तिब्बत और मध्य एशिया के 10,000 से अधिक मेधावी विद्वान और 2,000 शिक्षक यहां तर्कशास्त्र, दर्शन, खगोल विज्ञान और उन्नत चिकित्सा का अध्ययन करने के लिए एकत्र हुए।\n* **धर्मगंज**: इसके पौराणिक बहुमंजिला पुस्तकालय परिसर में ताड़ के पत्तों और भोजपत्र की सैकड़ों-हजारों दुर्लभ हस्तलिखित पांडुलिपियां सुरक्षित थीं।\n\nनालंदा सार्वभौमिक ज्ञान की निडर खोज के लिए मानवता की सबसे राजसी प्राचीन श्रद्धांजलि के रूप में खड़ा है।"
    },
    "event-sher-shah-patna-refounding-1541": {
        "en": "### The Revival of a Forgotten Metropolis\nFor centuries after the fall of the Pala empire, the once-glorious Pataliputra lay largely in ruins, eclipsed by the provincial capital of Bihar Sharif. However, in 1541 CE, the brilliant Afghan Emperor **Sher Shah Suri** visited these ancient ruins.\n\n### Strategic Fortification\nAs chronicled in Abbas Khan Sarwani's *Tarikh-i-Sher Shahi*, Sher Shah immediately recognized the enduring strategic and commercial dominance of its riverine location on the Ganga.\n* **The New Citadel**: He swiftly injected a massive sum of five lakh rupees into constructing a formidable riverside fort.\n* **Economic Resurgence**: He heavily incentivized merchants to settle around the fort, successfully reviving the ancient metropolis as a bustling commercial hub under its modern name, **Patna**.\n\nBy officially shifting the provincial administrative seat back to Patna, Sher Shah restored the city as the political and economic capital of Bihar—a prestigious status it has maintained without interruption to this very day.",
        "hi": "### एक विस्मृत महानगर का पुनरुत्थान\nपाल साम्राज्य के पतन के बाद सदियों तक, कभी गौरवशाली रहा पाटलिपुत्र काफी हद तक खंडहर बन चुका था, और प्रांतीय राजधानी बिहार शरीफ के सामने छिप गया था। हालाँकि, 1541 ईस्वी में, कुशाग्र अफगान सम्राट **शेरशाह सूरी** ने इन प्राचीन खंडहरों का दौरा किया।\n\n### सामरिक किलेबंदी\nअब्बास खां सरवानी की *'तारीख-ए-शेरशाही'* में वर्णित है कि शेरशाह ने तुरंत गंगा पर इसके नदीय स्थान के स्थायी रणनीतिक और वाणिज्यिक प्रभुत्व को पहचान लिया।\n* **नया दुर्ग**: उन्होंने नदी के किनारे एक दुर्जेय किले के निर्माण में पांच लाख रुपये की भारी राशि तेजी से लगाई।\n* **आर्थिक पुनरुद्धार**: उन्होंने व्यापारियों को किले के आसपास बसने के लिए भारी प्रोत्साहन दिया, और प्राचीन महानगर को इसके आधुनिक नाम, **पटना** के तहत एक हलचल भरे वाणिज्यिक केंद्र के रूप में सफलतापूर्वक पुनर्जीवित किया।\n\nप्रांतीय प्रशासनिक गद्दी को आधिकारिक तौर पर वापस पटना स्थानांतरित करके, शेरशाह ने शहर को बिहार की राजनीतिक और आर्थिक राजधानी के रूप में बहाल किया—एक प्रतिष्ठित दर्जा जिसे इसने आज तक बिना किसी रुकावट के बनाए रखा है।"
    },
    "event-guru-gobind-singh-birth-1666": {
        "en": "### The Divine Light Manifests\nOn the extremely auspicious day of December 22, 1666, the historic city of Patna was blessed with the birth of **Gobind Rai** (who would become the Tenth Sikh Guru, **Guru Gobind Singh Ji**). He was born to the Ninth Guru, **Guru Tegh Bahadur Ji**, and **Mata Gujri Ji**.\n\n### A Childhood by the Ganga\nThe young Guru spent the first deeply formative years of his life in Patna. \n* **Early Education**: It was here, along the banks of the mighty Ganga, that he joyfully engaged in his childhood *Bal Leelas*, learned Sanskrit and Persian, and received his initial training in martial arts before eventually departing for Anandpur Sahib.\n\n### An Eternal Spiritual Bond\nTo honor his sacred birthplace, Maharaja Ranjit Singh later commissioned the construction of a majestic Gurdwara on the site. Today, **Takht Sri Harmandir Ji Patna Sahib** shines as one of the Five holy *Takhts* (thrones of temporal authority) of Sikhism, cementing a profound, eternal spiritual bond between the soils of Bihar and Punjab.",
        "hi": "### दिव्य प्रकाश का प्राकट्य\n22 दिसंबर 1666 के अत्यंत शुभ दिन, ऐतिहासिक नगर पटना को **गोबिंद राय** (जो बाद में दसवें सिख गुरु, **गुरु गोबिंद सिंह जी** बने) के जन्म का आशीर्वाद मिला। उनका जन्म नौवें गुरु, **गुरु तेग बहादुर जी**, और **माता गुजरी जी** के घर हुआ था।\n\n### गंगा किनारे का बचपन\nबाल गुरु ने अपने जीवन के शुरुआती, गहरे रचनात्मक वर्ष पटना में बिताए।\n* **प्रारंभिक शिक्षा**: यहीं, विशाल गंगा के तट पर, उन्होंने अपनी बचपन की *बाल लीलाओं* में खुशी-खुशी भाग लिया, संस्कृत और फारसी सीखी, और आनंदपुर साहिब के लिए प्रस्थान करने से पहले मार्शल आर्ट में अपना प्रारंभिक प्रशिक्षण प्राप्त किया।\n\n### एक शाश्वत आध्यात्मिक बंधन\nउनके पवित्र जन्मस्थान का सम्मान करने के लिए, महाराजा रणजीत सिंह ने बाद में इस स्थल पर एक भव्य गुरुद्वारे के निर्माण का आदेश दिया। आज, **तख्त श्री हरिमंदिर जी पटना साहिब** सिख धर्म के पांच पवित्र *तख्तों* (लौकिक सत्ता के सिंहासन) में से एक के रूप में चमकता है, जो बिहार और पंजाब की मिट्टी के बीच एक गहरा, शाश्वत आध्यात्मिक बंधन स्थापित करता है।"
    },
    "event-battle-of-buxar-1764": {
        "en": "### The Clash of Empires\nFought on October 22, 1764, the **Battle of Buxar** stands as the definitive military conflict that irreversibly altered the destiny of the Indian subcontinent. The highly disciplined British East India Company forces, commanded by **Major Hector Munro**, faced a massive tripartite Indian alliance.\n\n### The Tripartite Defeat\nThe combined forces of the deposed Nawab of Bengal (*Mir Qasim*), the Nawab of Awadh (*Shuja-ud-Daulah*), and the Mughal Emperor (*Shah Alam II*) were comprehensively outmaneuvered and decisively crushed on the plains of Katkauli.\n\n### The Transfer of Sovereignty\nThe catastrophic defeat resulted in the humiliating **Treaty of Allahabad (1765)**. \n* **The Diwani Rights**: Emperor Shah Alam II was forced to officially grant the *Diwani* (the sovereign right to collect land revenues) of Bengal, Bihar, and Orissa to the British.\nThis monumental event transformed a mere commercial trading venture into the absolute colonial masters of northern India, inaugurating nearly two centuries of British imperial rule.",
        "hi": "### साम्राज्यों का टकराव\n22 अक्टूबर 1764 को लड़ा गया **बक्सर का युद्ध** वह निर्णायक सैन्य संघर्ष है जिसने भारतीय उपमहाद्वीप के भाग्य को अपरिवर्तनीय रूप से बदल दिया। **मेजर हेक्टर मुनरो** के नेतृत्व में ब्रिटिश ईस्ट इंडिया कंपनी की अत्यधिक अनुशासित सेना का सामना एक विशाल त्रिपक्षीय भारतीय गठबंधन से हुआ।\n\n### त्रिपक्षीय हार\nबंगाल के अपदस्थ नवाब (*मीर कासिम*), अवध के नवाब (*शुजाउद्दौला*) और मुगल सम्राट (*शाह आलम द्वितीय*) की संयुक्त सेना को कतकौली के मैदान में पूरी तरह से मात दी गई और निर्णायक रूप से कुचल दिया गया।\n\n### संप्रभुता का हस्तांतरण\nइस विनाशकारी हार का परिणाम अपमानजनक **इलाहाबाद की संधि (1765)** के रूप में सामने आया।\n* **दीवानी अधिकार**: सम्राट शाह आलम द्वितीय को आधिकारिक तौर पर बंगाल, बिहार और उड़ीसा की *दीवानी* (भू-राजस्व वसूलने का संप्रभु अधिकार) अंग्रेजों को सौंपने के लिए मजबूर होना पड़ा।\nइस स्मारकीय घटना ने एक साधारण वाणिज्यिक व्यापार उद्यम को उत्तर भारत के पूर्ण औपनिवेशिक स्वामियों में बदल दिया, जिससे लगभग दो शताब्दियों के ब्रिटिश साम्राज्यवादी शासन की शुरुआत हुई।"
    },
    "event-bihar-diwas-formation-1912": {
        "en": "### The Struggle for Identity\nFor a long time under British rule, Bihar was relegated to a marginalized appendix of the massive Bengal Presidency, leading to severe administrative neglect. Prominent intellectuals, heavily led by the visionary **Dr. Sachchidananda Sinha** and journalist **Mahesh Narayan**, spearheaded a relentless constitutional crusade demanding 'Bihar for Biharis'.\n\n### The Royal Proclamation\nTheir persistent advocacy achieved a monumental victory when King George V announced the separation at the Delhi Durbar in 1911. The official gazette notification, establishing 'Bihar and Orissa' as a distinctly separate, independent province with Patna as its capital, took legal effect on **March 22, 1912**.\n\n### A Day of Pride\nThis watershed event marked the glorious political rebirth and restored the unique cultural identity of modern Bihar. Today, March 22 is commemorated globally with immense state-wide enthusiasm and cultural resonance as **Bihar Diwas**, celebrating the state's enduring heritage and pride.",
        "hi": "### पहचान का संघर्ष\nब्रिटिश शासन के तहत लंबे समय तक, बिहार को विशाल बंगाल प्रेसीडेंसी के एक हाशिए के परिशिष्ट के रूप में रखा गया था, जिससे गंभीर प्रशासनिक उपेक्षा हुई। प्रमुख बुद्धिजीवियों, जिनका नेतृत्व दूरदर्शी **डॉ. सच्चिदानंद सिन्हा** और पत्रकार **महेश नारायण** ने किया, ने 'बिहार बिहारियों के लिए' की मांग करते हुए एक अथक संवैधानिक अभियान का नेतृत्व किया।\n\n### शाही उद्घोषणा\nउनकी निरंतर वकालत ने 1911 में दिल्ली दरबार में किंग जॉर्ज पंचम द्वारा अलगाव की घोषणा के साथ एक स्मारकीय जीत हासिल की। आधिकारिक राजपत्र अधिसूचना, जिसने पटना को अपनी राजधानी के साथ 'बिहार और उड़ीसा' को एक अलग, स्वतंत्र प्रांत के रूप में स्थापित किया, **22 मार्च 1912** को कानूनी रूप से प्रभावी हुई।\n\n### गौरव का दिन\nइस ऐतिहासिक घटना ने आधुनिक बिहार के गौरवशाली राजनीतिक पुनर्जन्म को चिह्नित किया और इसकी अनूठी सांस्कृतिक पहचान को बहाल किया। आज, 22 मार्च को राज्य की स्थायी विरासत और गौरव का जश्न मनाते हुए, अपार राज्य-व्यापी उत्साह और सांस्कृतिक अनुनाद के साथ **'बिहार दिवस'** के रूप में विश्व स्तर पर मनाया जाता है।"
    },
    "event-champaran-satyagraha-1917": {
        "en": "### The Plight of the Ryots\nFor generations, the indigo *ryots* (tenant farmers) of Champaran had suffered unimaginable economic exploitation and physical abuse under the cruel European planters' *Tinkathia* system. Heeding the desperate pleas of local farmer **Raj Kumar Shukla**, **Mahatma Gandhi** arrived in the district on April 15, 1917.\n\n### The First Satyagraha\nThis marked the dawn of Gandhi's very first civil disobedience movement in India. \n* **Defiance**: Faced with immediate British police orders to leave the district (Section 144), Gandhi displayed tranquil, unshakable conviction, refusing to obey an unjust law and publicly courting arrest.\n* **Systematic Resistance**: The sheer moral force of his defiance mobilized tens of thousands of terrified peasants to step forward and officially record their horrific grievances.\n\n### The Triumph of Truth\nThe overwhelming grassroots evidence forced the colonial government to pass the **Champaran Agrarian Act of 1918**, legally dismantling the Tinkathia system forever. It successfully established *Satyagraha* as India's ultimate weapon of mass struggle.",
        "hi": "### रैयतों की दुर्दशा\nपीढ़ियों से, चंपारण के नील *रैयतों* (किरायेदार किसानों) ने क्रूर यूरोपीय बगान मालिकों की *तीनकठिया* प्रणाली के तहत अकल्पनीय आर्थिक शोषण और शारीरिक दुर्व्यवहार का सामना किया था। स्थानीय किसान **राजकुमार शुक्ल** की हताश अपीलों पर ध्यान देते हुए, **महात्मा गांधी** 15 अप्रैल 1917 को जिले में पहुंचे।\n\n### प्रथम सत्याग्रह\nइसने भारत में गांधीजी के पहले सविनय अवज्ञा आंदोलन की शुरुआत को चिह्नित किया।\n* **अवज्ञा**: जिले को छोड़ने के तत्काल ब्रिटिश पुलिस आदेशों (धारा 144) का सामना करते हुए, गांधीजी ने शांत, अडिग दृढ़ विश्वास प्रदर्शित किया, एक अन्यायपूर्ण कानून का पालन करने से इनकार कर दिया और सार्वजनिक रूप से गिरफ्तारी दी।\n* **व्यवस्थित प्रतिरोध**: उनकी अवज्ञा की शुद्ध नैतिक शक्ति ने हजारों भयभीत किसानों को आगे आने और अपनी भयानक शिकायतों को आधिकारिक रूप से दर्ज करने के लिए लामबंद किया।\n\n### सत्य की विजय\nभारी जमीनी सबूतों ने औपनिवेशिक सरकार को **चंपारण कृषि अधिनियम 1918** पारित करने के लिए मजबूर किया, जिसने कानूनी तौर पर तीनकठिया प्रणाली को हमेशा के लिए खत्म कर दिया। इसने सफलतापूर्वक *सत्याग्रह* को जन संघर्ष के भारत के अंतिम हथियार के रूप में स्थापित किया।"
    },
    "event-patna-secretariat-firing-1942": {
        "en": "### The Climax of the Quit India Movement\nWhen the British authorities ruthlessly arrested all prominent national leaders following the launch of the Quit India Movement in August 1942, a massive leadership vacuum was created. Refusing to let the movement die, the fearless students of Bihar spontaneously took the reins.\n\n### The March to the Secretariat\nOn **August 11, 1942**, thousands of courageous school and college students marched powerfully towards the Old Secretariat in Patna, firmly resolved to tear down the Union Jack and hoist the Indian National Tricolour atop the heavily guarded provincial headquarters.\n\n### Seven Immortal Martyrs\nFacing heavily armed Gurkha police acting on the direct orders of District Magistrate W. G. Archer, the unarmed students refused to back down. As bullets rained down, seven young boys took turns, stepping forward over the fallen bodies of their comrades to keep the Tricolour flying high before they themselves were gunned down. \nThis supreme, selfless sacrifice galvanized the entire state into a ferocious, uncontrollable anti-colonial uprising.",
        "hi": "### भारत छोड़ो आंदोलन का चरमोत्कर्ष\nअगस्त 1942 में भारत छोड़ो आंदोलन के शुरू होने के बाद जब ब्रिटिश अधिकारियों ने सभी प्रमुख राष्ट्रीय नेताओं को बेरहमी से गिरफ्तार कर लिया, तो एक बड़ा नेतृत्व خلا पैदा हो गया। आंदोलन को मरने न देने का संकल्प लेते हुए, बिहार के निडर छात्रों ने स्वतः ही बागडोर संभाल ली।\n\n### सचिवालय की ओर कूच\n**11 अगस्त 1942** को, हजारों साहसी स्कूली और कॉलेज के छात्र पटना के पुराने सचिवालय की ओर शक्तिशाली रूप से मार्च कर गए, और भारी सुरक्षा वाले प्रांतीय मुख्यालय के ऊपर से यूनियन जैक को फाड़ने और भारतीय राष्ट्रीय तिरंगा फहराने का दृढ़ संकल्प लिया।\n\n### सात अमर शहीद\nजिलाधिकारी डब्ल्यू. जी. आर्चर के सीधे आदेश पर कार्रवाई कर रही भारी हथियारों से लैस गोरखा पुलिस का सामना करते हुए, निहत्थे छात्रों ने पीछे हटने से इनकार कर दिया। जैसे ही गोलियों की बौछार हुई, सात युवा लड़कों ने बारी-बारी से अपने गिरे हुए साथियों के शवों के ऊपर से आगे बढ़कर तिरंगे को ऊंचा रखा, इससे पहले कि उन्हें भी गोलियों से भून दिया जाता।\nइस सर्वोच्च, निःस्वार्थ बलिदान ने पूरे राज्य को एक भयंकर, अनियंत्रित उपनिवेश-विरोधी विद्रोह में झोंक दिया।"
    },
    "event-total-revolution-jp-1974": {
        "en": "### The Gathering Storm\nIn the early 1970s, post-independence India was severely plagued by rising unemployment, rampant inflation, political authoritarianism, and deep-seated systemic corruption. The disillusioned youth and students of Bihar initiated a massive agitation, seeking the moral guidance of the veteran socialist leader, **Loknayak Jayaprakash Narayan (JP)**.\n\n### The Call for Sampoorna Kranti\nOn **June 5, 1974**, JP addressed an ocean of humanity—over 500,000 resolute citizens—at the historic Gandhi Maidan in Patna. It was here that he famously blew the bugle for **'Sampoorna Kranti' (Total Revolution)**.\n\n### A Seven-Tiered Transformation\nJP did not merely demand a change in government; he called for an absolute, radical transformation across seven distinct spheres of society: social, economic, political, cultural, ideological, educational, and spiritual. \nThis monumental clarion call rapidly snowballed into a nationwide democratic uprising. It stood as the primary moral force that fiercely resisted the imposition of the Emergency and successfully brought about India's first non-Congress democratic government in 1977.",
        "hi": "### तूफ़ान का जमावड़ा\n1970 के दशक की शुरुआत में, स्वतंत्रता के बाद का भारत बढ़ती बेरोजगारी, अनियंत्रित मुद्रास्फीति, राजनीतिक सत्तावाद और गहरे जड़ जमा चुके प्रणालीगत भ्रष्टाचार से बुरी तरह त्रस्त था। बिहार के मोहभंग युवाओं और छात्रों ने दिग्गज समाजवादी नेता, **लोकनायक जयप्रकाश नारायण (जेपी)** के नैतिक मार्गदर्शन की मांग करते हुए एक व्यापक आंदोलन शुरू किया।\n\n### संपूर्ण क्रांति का आह्वान\n**5 जून 1974** को, जेपी ने पटना के ऐतिहासिक गांधी मैदान में मानवता के एक महासागर—5,00,000 से अधिक दृढ़ नागरिकों—को संबोधित किया। यहीं पर उन्होंने **'संपूर्ण क्रांति'** का प्रसिद्ध बिगुल फूंका था।\n\n### सात-स्तरीय परिवर्तन\nजेपी ने केवल सरकार में बदलाव की मांग नहीं की; उन्होंने समाज के सात अलग-अलग क्षेत्रों: सामाजिक, आर्थिक, राजनीतिक, सांस्कृतिक, वैचारिक, शैक्षिक और आध्यात्मिक में पूर्ण, आमूल-चूल परिवर्तन का आह्वान किया।\nयह स्मारकीय आह्वान तेजी से एक राष्ट्रव्यापी लोकतांत्रिक विद्रोह में बदल गया। यह प्राथमिक नैतिक शक्ति के रूप में खड़ा था जिसने आपातकाल को लागू करने का कड़ा विरोध किया और सफलतापूर्वक 1977 में भारत की पहली गैर-कांग्रेसी लोकतांत्रिक सरकार लाई।"
    }
}

for item in data['data']:
    if item['id'] in updates:
        item['description'] = updates[item['id']]

with open(filepath, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
    f.write('\n')
