import json

filepath = '/media/amit/Other1/webdevelopment/github/mahavyomastudio-apps/app_04_bihar_explorer/src/data/bihar-knowledge/02-history/freedom-movement.json'
with open(filepath, 'r', encoding='utf-8') as f:
    data = json.load(f)

updates = {
    "revolt-of-1857-veer-kunwar-singh": {
        "en": "### The Lion of Jagdishpur\nWhen the historic Sepoy Mutiny erupted in July 1857, the rebel soldiers of the Danapur cantonment marched straight to Jagdishpur, seeking leadership. There, the 80-year-old Rajput chieftain **Babu Kunwar Singh** took charge, transforming a local uprising into a massive anti-colonial war.\n\n### The Epic Campaigns\n* **Liberation of Arrah**: Demonstrating supreme tactical brilliance, Veer Kunwar Singh rapidly liberated Arrah and inflicted heavy casualties on the British forces.\n* **The Guerrilla War**: Alongside his brother **Babu Amar Singh**, he conducted relentless guerrilla campaigns across Bihar and eastern Uttar Pradesh.\n* **The Supreme Sacrifice**: In a legendary act of unparalleled bravery, while crossing the River Ganga, his arm was shattered by a British bullet. Without hesitation, the octogenarian severed his own arm with his sword and offered it to Mother Ganga.\n\n### The Final Victory\nReturning to Jagdishpur, he decisively defeated Captain Le Grand's British forces on **April 23, 1858**, succumbing to his severe battle injuries three days later as a victorious, unconquered sovereign.",
        "hi": "### जगदीशपुर का सिंह\nजब जुलाई 1857 में ऐतिहासिक सिपाही विद्रोह भड़का, तो दानापुर छावनी के बागी सैनिक नेतृत्व की तलाश में सीधे जगदीशपुर पहुंचे। वहां, 80 वर्षीय राजपूत सरदार **बाबू कुंवर सिंह** ने कमान संभाली, और एक स्थानीय विद्रोह को बड़े पैमाने के औपनिवेशिक विरोधी युद्ध में बदल दिया।\n\n### महाकाव्य अभियान\n* **आरा की मुक्ति**: सर्वोच्च सामरिक प्रतिभा का प्रदर्शन करते हुए, वीर कुंवर सिंह ने तेजी से आरा को मुक्त कराया और ब्रिटिश सेना को भारी नुकसान पहुंचाया।\n* **छापामार युद्ध**: अपने अनुज **बाबू अमर सिंह** के साथ मिलकर, उन्होंने पूरे बिहार और पूर्वी उत्तर प्रदेश में अथक छापामार अभियान चलाए।\n* **सर्वोच्च बलिदान**: अद्वितीय वीरता के एक अमर कार्य में, गंगा नदी पार करते समय ब्रिटिश गोली से उनकी बांह छलनी हो गई। बिना किसी हिचकिचाहट के, 80 वर्षीय योद्धा ने अपनी ही तलवार से अपनी बांह काट ली और उसे गंगा मैया को समर्पित कर दिया।\n\n### अंतिम विजय\nजगदीशपुर लौटकर, उन्होंने **23 अप्रैल 1858** को कैप्टन ली ग्रैंड की ब्रिटिश सेना को निर्णायक रूप से पराजित किया। तीन दिन बाद एक अजेय, विजयी संप्रभु के रूप में युद्ध के गंभीर घावों के कारण उन्होंने प्राण त्याग दिए।"
    },
    "champaran-satyagraha-1917": {
        "en": "### The Cry of the Peasants\nFor decades, the indigo farmers of Champaran were ruthlessly exploited under the oppressive Tinkathia system. Answering the desperate call of local farmer **Raj Kumar Shukla**, **Mahatma Gandhi** arrived in Motihari on April 15, 1917, embarking on his very first Satyagraha experiment on Indian soil.\n\n### The Path of Non-Violence\n* **Defying Unjust Orders**: Gandhi boldly disobeyed British expulsion orders in the Motihari court, declaring his willingness to face imprisonment for the sake of justice.\n* **Grassroots Survey**: Alongside stalwarts like *Dr. Rajendra Prasad* and *Dr. Anugrah Narayan Sinha*, he systematically documented the grievances of thousands of terrified peasants.\n\n### The Historic Victory\nThe immense public pressure forced the British government to form the Champaran Agrarian Enquiry Committee. This culminated in the **Champaran Agrarian Act of 1918**, which legally abolished the coercive Tinkathia system forever. This profound success effectively transformed Mohandas into the *Mahatma* of the Indian masses.",
        "hi": "### किसानों की पुकार\nदशकों तक, चंपारण के नील किसानों का दमनकारी तीनकठिया प्रणाली के तहत बेरहमी से शोषण किया गया। स्थानीय किसान **राजकुमार शुक्ल** की गुहार का उत्तर देते हुए, **महात्मा गांधी** 15 अप्रैल 1917 को मोतिहारी पहुंचे, और भारतीय धरती पर अपना पहला सत्याग्रह प्रयोग शुरू किया।\n\n### अहिंसा का मार्ग\n* **अन्यायपूर्ण आदेशों की अवहेलना**: गांधीजी ने मोतिहारी अदालत में ब्रिटिश निष्कासन आदेशों की निर्भीकता से अवहेलना की, और न्याय की खातिर जेल जाने की इच्छा व्यक्त की।\n* **जमीनी सर्वेक्षण**: *डॉ. राजेन्द्र प्रसाद* और *डॉ. अनुग्रह नारायण सिंह* जैसे दिग्गजों के साथ, उन्होंने हजारों भयभीत किसानों की शिकायतों को व्यवस्थित रूप से दर्ज किया।\n\n### ऐतिहासिक विजय\nभारी जन-दबाव ने ब्रिटिश सरकार को चंपारण कृषि जांच समिति बनाने के लिए मजबूर कर दिया। इसके परिणामस्वरूप **चंपारण कृषि अधिनियम 1918** पारित हुआ, जिसने शोषणकारी तीनकठिया प्रथा को हमेशा के लिए समाप्त कर दिया। इस बड़ी सफलता ने मोहनदास को भारतीय जनमानस का *'महात्मा'* बना दिया।"
    },
    "non-cooperation-and-bihar-vidyapeeth": {
        "en": "### The Wave of National Awakening\nDuring the roaring Non-Cooperation Movement (1920–1922), Bihar emerged as a formidable center of national education and economic boycott. Top legal luminaries like **Dr. Rajendra Prasad** and **Dr. Sri Krishna Sinha** famously surrendered their lucrative legal practices to join the struggle.\n\n### Pillars of Resistance\n* **Sadaqat Ashram**: Renowned nationalist **Maulana Mazharul Haque** donated his sprawling land in Patna to establish *Sadaqat Ashram* (Abode of Truth). It became the nerve center of the freedom movement in Bihar and the publication base for his nationalist journal, *The Motherland*.\n* **Bihar Vidyapeeth**: To provide indigenous education to students who boldly boycotted British government institutions, Mahatma Gandhi personally inaugurated **Bihar Vidyapeeth** on February 6, 1921, with Dr. Rajendra Prasad serving as its visionary first Principal.\n\nThrough peaceful picketing, spinning of Khadi, and unwavering unity, Bihar set a stellar example of mass non-violent resistance.",
        "hi": "### राष्ट्रीय जागरण की लहर\nउग्र असहयोग आंदोलन (1920-1922) के दौरान, बिहार राष्ट्रीय शिक्षा और आर्थिक बहिष्कार के एक दुर्जेय केंद्र के रूप में उभरा। **डॉ. राजेन्द्र प्रसाद** और **डॉ. श्रीकृष्ण सिंह** जैसे शीर्ष वकीलों ने संघर्ष में शामिल होने के लिए अपनी आकर्षक वकालत का त्याग कर दिया।\n\n### प्रतिरोध के स्तंभ\n* **सदाकत आश्रम**: प्रसिद्ध राष्ट्रवादी **मौलाना मजहरुल हक** ने *सदाकत आश्रम* (सत्य का निवास) स्थापित करने के लिए पटना में अपनी जमीन दान कर दी। यह बिहार में स्वतंत्रता आंदोलन का मुख्य केंद्र और उनके राष्ट्रवादी पत्र *'द मदरलैंड'* का प्रकाशन आधार बन गया।\n* **बिहार विद्यापीठ**: ब्रिटिश सरकारी संस्थानों का साहसपूर्वक बहिष्कार करने वाले छात्रों को स्वदेशी शिक्षा प्रदान करने के लिए, महात्मा गांधी ने व्यक्तिगत रूप से 6 फरवरी 1921 को **बिहार विद्यापीठ** का उद्घाटन किया, जिसमें डॉ. राजेन्द्र प्रसाद ने इसके प्रथम दूरदर्शी प्राचार्य के रूप में कार्य किया।\n\nशांतिपूर्ण पिकेटिंग, खादी कताई और अटूट एकता के माध्यम से, बिहार ने सामूहिक अहिंसक प्रतिरोध का एक शानदार उदाहरण प्रस्तुत किया।"
    },
    "kisan-sabha-movement-sahajanand": {
        "en": "### The Awakening of the Peasantry\nIn November 1929, the fiery ascetic **Swami Sahajanand Saraswati** (*Kisan Pran*) laid the foundation of the **Bihar Provincial Kisan Sabha** (BPKS) at the historic Sonepur Fair. The primary objective was to politically mobilize peasants against crippling Zamindari rents and brutal, unlawful evictions from *Bakasht* lands.\n\n### From Province to Nation\n* **All India Ascendancy**: The movement's massive success in Bihar catapulted it to the national stage. In April 1936, BPKS evolved into the **All India Kisan Sabha** at Lucknow, with Swami Sahajanand unanimously elected as its first President.\n* **Militant Non-Violence**: The movement saw fierce yet non-violent peasant struggles, notably the *Barahiya Tal* resistance led by **Karyanand Sharma** and the *Reora Satyagraha* led by **Yadunandan Sharma**.\n\n### The Final Outcome\nThis intense agrarian mobilization terrified the landed elite and ultimately laid the irreversible groundwork for the pioneering Zamindari abolition laws enacted in post-independence India.",
        "hi": "### किसानों का जागरण\nनवंबर 1929 में, उग्र संन्यासी **स्वामी सहजानंद सरस्वती** (*किसान प्राण*) ने ऐतिहासिक सोनपुर मेले में **बिहार प्रांतीय किसान सभा** (BPKS) की नींव रखी। इसका मुख्य उद्देश्य जमींदारों के कमरतोड़ लगान और *बकाश्त* भूमि से क्रूर, अवैध बेदखली के खिलाफ किसानों को राजनीतिक रूप से लामबंद करना था।\n\n### प्रांत से राष्ट्र तक\n* **अखिल भारतीय उत्कर्ष**: बिहार में आंदोलन की भारी सफलता ने इसे राष्ट्रीय मंच पर पहुंचा दिया। अप्रैल 1936 में, लखनऊ में BPKS **अखिल भारतीय किसान सभा** के रूप में विकसित हुई, जिसके प्रथम अध्यक्ष के रूप में स्वामी सहजानंद को सर्वसम्मति से चुना गया।\n* **उग्र अहिंसा**: इस आंदोलन ने भीषण लेकिन अहिंसक किसान संघर्ष देखे, विशेष रूप से **कार्यानंद शर्मा** के नेतृत्व में *बड़हिया टाल* का प्रतिरोध और **यदुनंदन शर्मा** के नेतृत्व में *रेवड़ा सत्याग्रह*।\n\n### अंतिम परिणाम\nइस तीव्र कृषि लामबंदी ने जमींदार वर्ग को डरा दिया और अंततः स्वतंत्रता के बाद भारत में लागू किए गए ऐतिहासिक जमींदारी उन्मूलन कानूनों के लिए एक अपरिवर्तनीय आधार तैयार किया।"
    },
    "salt-satyagraha-bihar-1930": {
        "en": "### Breaking the Salt Law\nDespite being a landlocked province, Bihar enthusiastically plunged into the Salt Satyagraha in April 1930. Patriots in Champaran and Saran creatively defied the draconian British salt tax by manufacturing salt from saline soil (*Kharimati*). In Patna, thousands gathered at **Nakhas Pond** under the leadership of **Ambika Kant Sinha**, bravely facing brutal police baton charges while boiling saline water.\n\n### The Chaukidari Tax Boycott\nRealizing the geographic limitations of salt production, Bihar swiftly innovated, turning the Civil Disobedience Movement into a massive, militant campaign refusing to pay the **'Chaukidari Tax'** (a tax forcibly levied to fund the auxiliary rural police).\n* **Administrative Paralysis**: This mass refusal, heavily concentrated in Saran, Champaran, and Munger, utterly paralyzed the British rural administrative and surveillance machinery.\n\nThis unique dual-pronged strategy showcased the exceptional political ingenuity and fearless spirit of the Bihari masses during the freedom struggle.",
        "hi": "### नमक कानून तोड़ना\nसमुद्र तट से विहीन प्रांत होने के बावजूद, बिहार अप्रैल 1930 में पूरे उत्साह के साथ नमक सत्याग्रह में कूद पड़ा। चंपारण और सारण के देशभक्तों ने नमकीन मिट्टी (*खारी माटी*) से नमक बनाकर क्रूर ब्रिटिश नमक कर की रचनात्मक अवहेलना की। पटना में, **अंबिका कांत सिन्हा** के नेतृत्व में हजारों लोग **नखास पिंड** पर एकत्र हुए, और खारा पानी उबालते हुए बहादुरी से पुलिस के क्रूर लाठीचार्ज का सामना किया।\n\n### चौकीदारी कर का बहिष्कार\nनमक उत्पादन की भौगोलिक सीमाओं को महसूस करते हुए, बिहार ने तेजी से नवाचार किया, और सविनय अवज्ञा आंदोलन को एक बड़े, उग्र अभियान में बदल दिया, जिसमें **'चौकीदारी कर'** (ग्रामीण पुलिस के वित्तपोषण के लिए जबरन लगाया गया कर) का भुगतान करने से साफ इनकार कर दिया गया।\n* **प्रशासनिक पंगुता**: सारण, चंपारण और मुंगेर में भारी रूप से केंद्रित इस सामूहिक बहिष्कार ने ब्रिटिश ग्रामीण प्रशासनिक और निगरानी तंत्र को पूरी तरह से पंगु बना दिया।\n\nइस अनूठी दोहरी रणनीति ने स्वतंत्रता संग्राम के दौरान बिहार की जनता की असाधारण राजनीतिक सरलता और निडर भावना का प्रदर्शन किया।"
    },
    "patna-secretariat-firing-seven-martyrs": {
        "en": "### The Uprising of August '42\nOn **August 11, 1942**, during the explosive climax of the Quit India Movement, with all top national leaders imprisoned, the youth of Bihar took charge. Thousands of brave student demonstrators converged upon the Old Secretariat in Patna, determined to hoist the Indian National Tricolour on the administrative nerve center of the province.\n\n### The Supreme Sacrifice\nViewing the massive crowd as a severe threat, District Magistrate **W. G. Archer** cold-bloodedly ordered the armed police to open fire. In an astonishing display of courage, as one student fell to British bullets, another stepped forward to keep the flag flying high. **Seven young students**, aged between 14 and 20, laid down their lives that day in a hail of gunfire.\n\n### The Immortal Memorial\nThe sacrifice of these seven heroes ignited an unprecedented rebellion across Bihar, completely paralyzing British communication and rail lines for weeks. Today, the majestic bronze **Shaheed Smarak** (Martyrs' Memorial) stands tall outside the Bihar Vidhan Sabha, immortalizing their indomitable spirit.",
        "hi": "### अगस्त 1942 का विद्रोह\n**11 अगस्त 1942** को, भारत छोड़ो आंदोलन के विस्फोटक चरमोत्कर्ष के दौरान, जब सभी शीर्ष राष्ट्रीय नेता जेल में थे, बिहार के युवाओं ने कमान संभाली। हजारों वीर छात्र प्रदर्शनकारी प्रांत के प्रशासनिक केंद्र पटना के पुराने सचिवालय पर भारतीय राष्ट्रीय तिरंगा फहराने के दृढ़ संकल्प के साथ एकत्र हुए।\n\n### सर्वोच्च बलिदान\nविशाल भीड़ को एक गंभीर खतरे के रूप में देखते हुए, जिलाधिकारी **डब्ल्यू. जी. आर्चर** ने क्रूरतापूर्वक सशस्त्र पुलिस को गोली चलाने का आदेश दिया। अदम्य साहस के एक आश्चर्यजनक प्रदर्शन में, जब एक छात्र ब्रिटिश गोलियों से गिरता, तो दूसरा झंडे को ऊंचा रखने के लिए आगे आ जाता। 14 से 20 वर्ष की आयु के **सात युवा छात्रों** ने उस दिन गोलियों की बौछार में अपने प्राणों की आहुति दे दी।\n\n### अमर स्मारक\nइन सात नायकों के बलिदान ने पूरे बिहार में एक अभूतपूर्व विद्रोह प्रज्वलित कर दिया, जिससे हफ्तों तक ब्रिटिश संचार और रेल लाइनें पूरी तरह ठप हो गईं। आज, बिहार विधानसभा के बाहर कांसे की भव्य **'शहीद स्मारक'** प्रतिमा शान से खड़ी है, जो उनकी अदम्य भावना को अमर करती है।"
    },
    "azad-dasta-jayaprakash-narayan": {
        "en": "### The Great Escape\nOn the dark Diwali night of November 9, 1942, socialist visionary **Loknayak Jayaprakash Narayan (JP)** executed a daring, legendary escape from the high-security walls of Hazaribagh Central Jail along with five trusted comrades. \n\n### The Freedom Brigade\nDeep within the impenetrable Terai forests of Nepal (Bakro Island), JP, joined by **Dr. Ram Manohar Lohia**, established the highly secretive **'Azad Dasta'** (Freedom Brigade). \n* **Guerrilla Warfare**: The objective was to train patriotic youths in advanced guerrilla warfare, sabotage, and disruption tactics.\n* **Crippling the Empire**: The Azad Dasta systematically uprooted railway tracks, severed telegraph lines, and destroyed bridges, completely destabilizing the British military supply logistics during World War II.\n\n### The Underground Flame\nWhen all constitutional Congress bodies were banned and leaders jailed, the Azad Dasta successfully kept the revolutionary flame of the Quit India movement burning fiercely from the underground.",
        "hi": "### ऐतिहासिक पलायन\n9 नवंबर 1942 की अंधेरी दिवाली की रात को, समाजवादी दूरदर्शी **लोकनायक जयप्रकाश नारायण (जेपी)** ने अपने पांच भरोसेमंद साथियों के साथ हजारीबाग सेंट्रल जेल की उच्च सुरक्षा दीवारों से एक साहसिक, ऐतिहासिक पलायन को अंजाम दिया।\n\n### आजाद दस्ता\nनेपाल के दुर्गम तराई जंगलों (बकरा टापू) के भीतर, जेपी ने **डॉ. राम मनोहर लोहिया** के साथ मिलकर अत्यंत गुप्त **'आजाद दस्ता'** की स्थापना की।\n* **गुरिल्ला युद्ध**: इसका उद्देश्य देशभक्त युवाओं को उन्नत छापामार युद्ध, तोड़फोड़ और विघटनकारी रणनीति में प्रशिक्षित करना था।\n* **साम्राज्य को पंगु बनाना**: आजाद दस्ते ने व्यवस्थित रूप से रेलवे पटरियों को उखाड़ दिया, टेलीग्राफ लाइनों को काट दिया, और पुलों को नष्ट कर दिया, जिससे द्वितीय विश्व युद्ध के दौरान ब्रिटिश सैन्य आपूर्ति पूरी तरह से बाधित हो गई।\n\n### भूमिगत ज्वाला\nजब सभी संवैधानिक कांग्रेस संस्थाओं पर प्रतिबंध लगा दिया गया और नेताओं को जेल में डाल दिया गया, तब आजाद दस्ते ने भारत छोड़ो आंदोलन की क्रांतिकारी ज्वाला को भूमिगत रहकर पूरी ताकत से जलाए रखा।"
    },
    "individual-satyagraha-bihar-1940": {
        "en": "### The Defense of Free Speech\nIn late 1940, protesting against India being dragged into World War II without its consent, Mahatma Gandhi initiated the 'Individual Satyagraha' campaign. The goal was to peacefully assert the fundamental right to freedom of speech against involuntary imperialist conscription.\n\n### Bihar's Frontline Leaders\n* **The First Satyagrahi**: The immensely popular **Dr. Sri Krishna Sinha** (*Sri Babu*) was selected as the first Individual Satyagrahi for Bihar. On November 27, 1940, he delivered a powerful anti-war speech in Patna and gracefully offered himself for arrest.\n* **The Second Satyagrahi**: Shortly after, on December 1, 1940, **Dr. Anugrah Narayan Sinha** (*Anugrah Babu*) courted arrest in Patna as the state's second Satyagrahi.\n\n### Mass Participation\nFollowing their lead, hundreds of dedicated Satyagrahis across various districts of Bihar stepped forward, calmly violating wartime ordinances and filling British jails, deeply unnerving the colonial administration.",
        "hi": "### अभिव्यक्ति की स्वतंत्रता की रक्षा\n1940 के अंत में, भारत की सहमति के बिना उसे द्वितीय विश्व युद्ध में धकेलने के विरोध में, महात्मा गांधी ने 'व्यक्तिगत सत्याग्रह' अभियान शुरू किया। इसका लक्ष्य साम्राज्यवादी युद्ध में अनिवार्य भर्ती के खिलाफ अभिव्यक्ति की स्वतंत्रता के मौलिक अधिकार का शांतिपूर्ण ढंग से दावा करना था।\n\n### बिहार के अग्रणी नेता\n* **प्रथम सत्याग्रही**: बेहद लोकप्रिय **डॉ. श्रीकृष्ण सिंह** (*श्रीबाबू*) को बिहार के प्रथम व्यक्तिगत सत्याग्रही के रूप में चुना गया। 27 नवंबर 1940 को, उन्होंने पटना में एक जोरदार युद्ध-विरोधी भाषण दिया और अपनी गिरफ्तारी दी।\n* **द्वितीय सत्याग्रही**: इसके कुछ ही समय बाद, 1 दिसंबर 1940 को, **डॉ. अनुग्रह नारायण सिंह** (*अनुग्रह बाबू*) ने राज्य के दूसरे सत्याग्रही के रूप में पटना में गिरफ्तारी दी।\n\n### जनभागीदारी\nउनके पदचिह्नों पर चलते हुए, बिहार के विभिन्न जिलों के सैकड़ों समर्पित सत्याग्रही आगे आए, शांतिपूर्वक युद्धकालीन अध्यादेशों का उल्लंघन किया और ब्रिटिश जेलों को भर दिया, जिससे औपनिवेशिक प्रशासन बुरी तरह घबरा गया।"
    },
    "role-of-women-freedom-fighters": {
        "en": "### The Vanguard of Resistance\nThroughout the freedom struggle, the women of Bihar stepped out of the confines of traditional domesticity to play an inspiring, frontline role in the national movement. They transformed non-violent resistance into a mass phenomenon.\n\n### Economic and Social Empowerment\n* **Prabhavati Devi**: A staunch Gandhian freedom fighter (and wife of JP), **Prabhavati Devi** established the *Mahila Charkha Samiti* in Patna. This institution crucially empowered women economically through spinning Khadi and politically organized them for mass resistance.\n* **Direct Action**: During the Salt Satyagraha (1930) and the Quit India Movement (1942), fearless leaders like *Saraswati Devi, Radhika Devi,* and *Malti Devi* led massive processions. They successfully picketed foreign cloth shops and liquor stalls, defying strict prohibitory orders.\n\n### Enduring Legacy\nUndeterred by violent baton charges and rigorous imprisonments, these brave *Viraanganas* (heroines) laid a robust, unshakeable foundation for women's civic participation and social reform in modern Bihar.",
        "hi": "### प्रतिरोध की अग्रिम पंक्ति\nस्वतंत्रता संग्राम के दौरान, बिहार की महिलाएं पारंपरिक घरेलू चारदीवारी से बाहर निकलकर राष्ट्रीय आंदोलन में एक प्रेरणादायक और अग्रणी भूमिका निभाने के लिए आगे आईं। उन्होंने अहिंसक प्रतिरोध को एक जन आंदोलन में बदल दिया।\n\n### आर्थिक और सामाजिक सशक्तिकरण\n* **प्रभावती देवी**: एक कट्टर गांधीवादी स्वतंत्रता सेनानी (और जेपी की धर्मपत्नी), **प्रभावती देवी** ने पटना में *महिला चरखा समिति* की स्थापना की। इस संस्था ने खादी कताई के माध्यम से महिलाओं को आर्थिक रूप से सशक्त बनाया और उन्हें सामूहिक प्रतिरोध के लिए राजनीतिक रूप से संगठित किया।\n* **सीधी कार्रवाई**: नमक सत्याग्रह (1930) और भारत छोड़ो आंदोलन (1942) के दौरान, *सरस्वती देवी, राधिका देवी* और *मालती देवी* जैसी निडर नेताओं ने विशाल जुलूसों का नेतृत्व किया। उन्होंने सख्त निषेधाज्ञाओं की धज्जियां उड़ाते हुए विदेशी कपड़ों की दुकानों और शराब के ठेकों पर सफलतापूर्वक धरना दिया।\n\n### स्थायी विरासत\nहिंसक लाठीचार्ज और कठोर कारावास से विचलित हुए बिना, इन बहादुर *वीरांगनाओं* ने आधुनिक बिहार में महिलाओं की नागरिक भागीदारी और सामाजिक सुधार के लिए एक मजबूत, अडिग नींव रखी।"
    },
    "santhal-hul-rebellion-1855": {
        "en": "### The Spark of Rebellion\nLong before the Sepoy Mutiny, the **Santhal Hul (Rebellion) of 1855** erupted as one of the fiercest armed tribal uprisings in Indian history. It was triggered by the relentless exploitation of the Santhal tribes in the *Damin-i-Koh* region by oppressive British tax collectors, corrupt police (*Darogas*), and usurious money-lenders (*Mahajans*).\n\n### The Declaration of Sovereignty\n* **The Four Brothers**: The uprising was brilliantly spearheaded by four brothers—**Sidhu, Kanhu, Chand,** and **Bhairav**—supported fiercely by their sisters **Phulo** and **Jhano**.\n* **The Assembly at Bhagnadih**: On **June 30, 1855**, over 30,000 Santhals mobilized at Bhagnadih, formally declaring the end of Company rule and establishing independent tribal sovereignty.\n\n### The Aftermath\nArmed merely with bows, arrows, and axes, they courageously fought the modern British artillery at Kahalgaon and Pirpainti. Though the rebellion was ultimately crushed with immense brutality, it forced the terrified British administration to enact Act XXXVII of 1855, creating the protected **Santhal Pargana Non-Regulation District** to safeguard customary tribal rights.",
        "hi": "### विद्रोह की चिंगारी\nसिपाही विद्रोह से बहुत पहले, **1855 का संथाल हूल (विद्रोह)** भारतीय इतिहास के सबसे भयंकर सशस्त्र आदिवासी विद्रोहों में से एक के रूप में भड़का। यह दमनकारी ब्रिटिश कर संग्रहकर्ताओं, भ्रष्ट पुलिस (*दरोगा*) और सूदखोर महाजनों द्वारा *दामिन-ए-कोह* क्षेत्र में संथाल जनजातियों के निरंतर शोषण के कारण उत्पन्न हुआ था।\n\n### संप्रभुता की घोषणा\n* **चार भाई**: इस विद्रोह का शानदार नेतृत्व चार भाइयों—**सिदो, कान्हू, चांद** और **भैरव**—ने किया, जिन्हें उनकी बहनों **फूलो** और **झानो** का भरपूर समर्थन प्राप्त था।\n* **भगनाडीह में सभा**: **30 जून 1855** को, भगनाडीह में 30,000 से अधिक संथाल एकत्र हुए, जिन्होंने औपचारिक रूप से कंपनी शासन के अंत की घोषणा की और स्वतंत्र आदिवासी संप्रभुता की स्थापना की।\n\n### परिणाम\nकेवल धनुष, तीर और कुल्हाड़ियों से लैस, उन्होंने कहलगांव और पीरपैंती में आधुनिक ब्रिटिश तोपखाने का साहसपूर्वक मुकाबला किया। यद्यपि विद्रोह को अंततः अत्यधिक क्रूरता के साथ कुचल दिया गया था, लेकिन इसने भयभीत ब्रिटिश प्रशासन को 1855 के अधिनियम 37 को लागू करने के लिए मजबूर कर दिया, जिससे आदिवासियों के पारंपरिक अधिकारों की रक्षा के लिए संरक्षित **'संथाल परगना'** का गठन हुआ।"
    }
}

for item in data['data']:
    if item['id'] in updates:
        item['description'] = updates[item['id']]

with open(filepath, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
    f.write('\n')
